<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Сбор-и-обработка-данных" data-toc-modified-id="Сбор-и-обработка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Сбор и обработка данных</a></span><ul class="toc-item"><li><span><a href="#Изучение-данных-с-сайта-https://www.eliteprospects.com" data-toc-modified-id="Изучение-данных-с-сайта-https://www.eliteprospects.com-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Изучение данных с сайта <a href="https://www.eliteprospects.com" rel="nofollow" target="_blank">https://www.eliteprospects.com</a></a></span><ul class="toc-item"><li><span><a href="#Информация-об-игроках" data-toc-modified-id="Информация-об-игроках-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Информация об игроках</a></span></li><li><span><a href="#Информация-о-переходах-игроков" data-toc-modified-id="Информация-о-переходах-игроков-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Информация о переходах игроков</a></span></li><li><span><a href="#Персональные-данные" data-toc-modified-id="Персональные-данные-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Персональные данные</a></span></li><li><span><a href="#Статистика-игроков" data-toc-modified-id="Статистика-игроков-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>Статистика игроков</a></span></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-1.1.5"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li></ul></li><li><span><a href="#Предобработка-данных." data-toc-modified-id="Предобработка-данных.-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Предобработка данных.</a></span><ul class="toc-item"><li><span><a href="#Обработка-датафреймов." data-toc-modified-id="Обработка-датафреймов.-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Обработка датафреймов.</a></span><ul class="toc-item"><li><span><a href="#players_data---информацией-об-игроках." data-toc-modified-id="players_data---информацией-об-игроках.-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>players_data - информацией об игроках.</a></span></li><li><span><a href="#transfers---информацией-о-переходах-игроков." data-toc-modified-id="transfers---информацией-о-переходах-игроков.-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>transfers - информацией о переходах игроков.</a></span></li></ul></li><li><span><a href="#Объединение-датафреймов." data-toc-modified-id="Объединение-датафреймов.-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Объединение датафреймов.</a></span><ul class="toc-item"><li><span><a href="#Исходящие-трансферы." data-toc-modified-id="Исходящие-трансферы.-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Исходящие трансферы.</a></span></li><li><span><a href="#Входящие-трансферы." data-toc-modified-id="Входящие-трансферы.-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Входящие трансферы.</a></span></li><li><span><a href="#Общий-датафрейм." data-toc-modified-id="Общий-датафрейм.-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>Общий датафрейм.</a></span></li></ul></li></ul></li><li><span><a href="#Изучение-и-обработка-датафрема-на-основе-данных-с-сайта-https://en.khl.ru/" data-toc-modified-id="Изучение-и-обработка-датафрема-на-основе-данных-с-сайта-https://en.khl.ru/-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Изучение и обработка датафрема на основе данных с сайта <a href="https://en.khl.ru/" rel="nofollow" target="_blank">https://en.khl.ru/</a></a></span><ul class="toc-item"><li><span><a href="#players---информация-о-периодах-нахождения-игроков-в-командах." data-toc-modified-id="players---информация-о-периодах-нахождения-игроков-в-командах.-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>players - информация о периодах нахождения игроков в командах.</a></span></li><li><span><a href="#stat---статистика-игроков" data-toc-modified-id="stat---статистика-игроков-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>stat - статистика игроков</a></span></li></ul></li><li><span><a href="#Топы" data-toc-modified-id="Топы-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Топы</a></span><ul class="toc-item"><li><span><a href="#Топ-15-игроков-по-количеству-команд-за-карьеру-в-КХЛ." data-toc-modified-id="Топ-15-игроков-по-количеству-команд-за-карьеру-в-КХЛ.-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Топ-15 игроков по количеству команд за карьеру в КХЛ.</a></span></li><li><span><a href="#Топ-15-игроков-по-количеству-переходов-за-карьеру-в-КХЛ." data-toc-modified-id="Топ-15-игроков-по-количеству-переходов-за-карьеру-в-КХЛ.-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Топ-15 игроков по количеству переходов за карьеру в КХЛ.</a></span></li><li><span><a href="#Топ-15-команд-по-количеству-игроков." data-toc-modified-id="Топ-15-команд-по-количеству-игроков.-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Топ-15 команд по количеству игроков.</a></span></li></ul></li><li><span><a href="#Визуализизация-переходов-игроков-между-командами." data-toc-modified-id="Визуализизация-переходов-игроков-между-командами.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Визуализизация переходов игроков между командами.</a></span><ul class="toc-item"><li><span><a href="#Sankey-Chart-диаграммы" data-toc-modified-id="Sankey-Chart-диаграммы-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span><strong>Sankey Chart</strong> диаграммы</a></span><ul class="toc-item"><li><span><a href="#Переходы-топ-20-игроков-между-командами-КХЛ." data-toc-modified-id="Переходы-топ-20-игроков-между-командами-КХЛ.-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>Переходы топ-20 игроков между командами КХЛ.</a></span></li><li><span><a href="#Переходы-игроков-между-топ-5-команд-КХЛ." data-toc-modified-id="Переходы-игроков-между-топ-5-команд-КХЛ.-5.1.2"><span class="toc-item-num">5.1.2&nbsp;&nbsp;</span>Переходы игроков между топ-5 команд КХЛ.</a></span></li></ul></li><li><span><a href="#Сhord-диаграммы" data-toc-modified-id="Сhord-диаграммы-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span><strong>Сhord</strong> диаграммы</a></span><ul class="toc-item"><li><span><a href="#Переходы-топ-20-игроков-между-командами" data-toc-modified-id="Переходы-топ-20-игроков-между-командами-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>Переходы топ-20 игроков между командами</a></span></li><li><span><a href="#Топ-20-по-количеству-переходов-между-двумя-командами." data-toc-modified-id="Топ-20-по-количеству-переходов-между-двумя-командами.-5.2.2"><span class="toc-item-num">5.2.2&nbsp;&nbsp;</span>Топ-20 по количеству переходов между двумя командами.</a></span></li></ul></li></ul></li><li><span><a href="#Поиск-одноклубников" data-toc-modified-id="Поиск-одноклубников-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Поиск одноклубников</a></span></li><li><span><a href="#Рассчет-числа-Лемтюгова.-Создание-графа." data-toc-modified-id="Рассчет-числа-Лемтюгова.-Создание-графа.-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Рассчет числа Лемтюгова. Создание графа.</a></span><ul class="toc-item"><li><span><a href="#Николай-Лемтюгов" data-toc-modified-id="Николай-Лемтюгов-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Николай Лемтюгов</a></span></li><li><span><a href="#Евгений-Лапенков" data-toc-modified-id="Евгений-Лапенков-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Евгений Лапенков</a></span></li><li><span><a href="#Либор-Касик" data-toc-modified-id="Либор-Касик-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Либор Касик</a></span></li></ul></li><li><span><a href="#Визуализация-графов." data-toc-modified-id="Визуализация-графов.-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Визуализация графов.</a></span><ul class="toc-item"><li><span><a href="#Топ-75,-библиотека-Networkx" data-toc-modified-id="Топ-75,-библиотека-Networkx-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Топ-75, библиотека Networkx</a></span></li><li><span><a href="#Топ-10,-библиотека-Holoview" data-toc-modified-id="Топ-10,-библиотека-Holoview-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Топ-10, библиотека Holoview</a></span></li><li><span><a href="#Топ-5,-библиотека-Holoview" data-toc-modified-id="Топ-5,-библиотека-Holoview-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>Топ-5, библиотека Holoview</a></span></li></ul></li><li><span><a href="#Проверка-гипотез" data-toc-modified-id="Проверка-гипотез-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Проверка гипотез</a></span><ul class="toc-item"><li><span><a href="#гипотеза-1:" data-toc-modified-id="гипотеза-1:-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>гипотеза 1:</a></span></li><li><span><a href="#гипотеза-2" data-toc-modified-id="гипотеза-2-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>гипотеза 2</a></span></li><li><span><a href="#гипотеза-3" data-toc-modified-id="гипотеза-3-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>гипотеза 3</a></span></li><li><span><a href="#гипотеза-4" data-toc-modified-id="гипотеза-4-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>гипотеза 4</a></span></li><li><span><a href="#гипотеза-5" data-toc-modified-id="гипотеза-5-9.5"><span class="toc-item-num">9.5&nbsp;&nbsp;</span>гипотеза 5</a></span></li><li><span><a href="#гипотеза-6" data-toc-modified-id="гипотеза-6-9.6"><span class="toc-item-num">9.6&nbsp;&nbsp;</span>гипотеза 6</a></span><ul class="toc-item"><li><span><a href="#вратари" data-toc-modified-id="вратари-9.6.1"><span class="toc-item-num">9.6.1&nbsp;&nbsp;</span>вратари</a></span></li><li><span><a href="#нападающие" data-toc-modified-id="нападающие-9.6.2"><span class="toc-item-num">9.6.2&nbsp;&nbsp;</span>нападающие</a></span><ul class="toc-item"><li><span><a href="#гол-+-пас" data-toc-modified-id="гол-+-пас-9.6.2.1"><span class="toc-item-num">9.6.2.1&nbsp;&nbsp;</span>гол + пас</a></span></li><li><span><a href="#показатель-+/-" data-toc-modified-id="показатель-+/--9.6.2.2"><span class="toc-item-num">9.6.2.2&nbsp;&nbsp;</span>показатель +/-</a></span></li></ul></li><li><span><a href="#защитники" data-toc-modified-id="защитники-9.6.3"><span class="toc-item-num">9.6.3&nbsp;&nbsp;</span>защитники</a></span><ul class="toc-item"><li><span><a href="#гол-+-пас" data-toc-modified-id="гол-+-пас-9.6.3.1"><span class="toc-item-num">9.6.3.1&nbsp;&nbsp;</span>гол + пас</a></span></li><li><span><a href="#показатель-+/-" data-toc-modified-id="показатель-+/--9.6.3.2"><span class="toc-item-num">9.6.3.2&nbsp;&nbsp;</span>показатель +/-</a></span></li></ul></li></ul></li></ul></li></ul></div>

# РЕТ-проект “Хоккей: расчет числа Лемтюгова”


# Описание проекта

# Цель проекта:
Создать аналог числа Эрдёша — Бэйкона для отечественных хоккеистов, называемый
числом Лемтюгова, чтобы измерять "близость" хоккеистов к Николаю Лемтюгову через команды, в
которых они играли.
Задачи проекта:
1. Собрать данные об отечественных хоккеистах и командах, в которых они играли.
2. Рассчитать число Лемтюгова для каждого хоккеиста.
3. Построить дэшборд или отчет с графами, отображающими связи между хоккеистами и количеством команд, через которые они были связаны.

## Сбор и обработка данных

* Были собраны 4 датасета:
    * players_data.csv - датасет из всех игроков, заигранных за команды КХЛ, начиная с сезона 2008-2009. Данные с сайта eliteprospects.com.
    * transfers.csv - датасет всех переходов игроков из всех лиг, первый трансфер 14/12/2007. Данные с сайта eliteprospects.com.
    * players_personal_data.csv - датасет с личными данными игроков
    * player_stats.csv - датасет со статистикой игроков


Необходимо исследовать данные и объединить датасеты в соответствии с
задачами.


### Изучение данных с сайта https://www.eliteprospects.com
Импортируем необходимые инструменты.

In [ ]:
!pip install scikit-image --quiet
!pip install datashader --quiet
!pip install holoviews==1.16 --quiet
!pip install bokeh==3.1.1 --quiet
!pip install ydata_profiling --quiet

In [ ]:
import pandas as pd
from ydata_profiling import ProfileReport
from datetime import datetime

import numpy as np

import scipy
from scipy.sparse import csr_matrix
from scipy.stats import ttest_ind

from tqdm import tqdm

from queue import Queue

import networkx as nx

#Основные графические библиотеки
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go


import holoviews as hv
import bokeh
from holoviews import opts, dim
import holoviews.plotting.bokeh
from bokeh.plotting import show, output_file
hv.extension('bokeh')
from holoviews.operation.datashader import datashade, bundle_graph


Output hidden; open in https://colab.research.google.com to view.

Создадим функцию для загрузки датафреймов и выводу информации по ним.

In [ ]:
def data_read_exam(file_path, index_col=False):
    """
    input:        file_path [object] - путь к файлу
    output:       data [DataFrame] - таблица данных
    description:  функция загружает таблицу функцией read_csv, выводит первые 5 строк на экран,
                  выводит информацию о данных методом info(), считает количество дубликатов
    """
    # читаем данные из .csv файла с помощью метода read_csv()
    if index_col == True:
        data = pd.read_csv(file_path, index_col=0)
    else:
        data = pd.read_csv(file_path)
    display(data.head())
    print(data.info())
    print('Количество дубликатов:', sum(data.duplicated()))
    return data

#### Информация об игроках

In [ ]:
try:
    players_data = data_read_exam('D:/jn/Masterskaya/Lemtyugov_number/players_data.csv')
except:
    players_data = data_read_exam('https://raw.githubusercontent.com/CurasaoRG/hockey_project/main/players_data.csv')

Team     Season                Player  Player_number  \
0  Salavat Yulaev Ufa  2008-2009          Sergei Belov             31   
1  Salavat Yulaev Ufa  2008-2009       Rafael Khakimov             31   
2  Salavat Yulaev Ufa  2008-2009         Vadim Tarasov              1   
3  Salavat Yulaev Ufa  2008-2009  Alexander Yeryomenko             30   
4  Salavat Yulaev Ufa  2008-2009       Miroslav Blatak             23   

  Position Captain  Born            Birthplace   Age  Height  Weight Stick  \
0        G     NaN  1982   St. Petersburg, RUS  40.0     180      78     L   
1        G     NaN  1990              Ufa, RUS  33.0     180      78     L   
2        G     NaN  1976  Ust-Kamenogorsk, KAZ  46.0     183      84     L   
3        G     NaN  1980           Moskva, RUS  43.0     180      78     L   
4        D     NaN  1982             Zlin, CZE  41.0     180      78     L   

                                         Player_link  
0  https://www.eliteprospects.com/player/19555/se...  
1  https://www.eliteprospects.com/player/47547/ra...  
2  https://www.eliteprospects.com/player/11990/va...  
3  https://www.eliteprospects.com/player/12286/al...  
4  https://www.eliteprospects.com/player/8421/mir...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14332 entries, 0 to 14331
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Team           14332 non-null  object 
 1   Season         14332 non-null  object 
 2   Player         14332 non-null  object 
 3   Player_number  14332 non-null  int64  
 4   Position       14332 non-null  object 
 5   Captain        1037 non-null   object 
 6   Born           14332 non-null  int64  
 7   Birthplace     14271 non-null  object 
 8   Age            14234 non-null  float64
 9   Height         14332 non-null  int64  
 10  Weight         14332 non-null  int64  
 11  Stick          14332 non-null  object 
 12  Player_link    14332 non-null  object 
dtypes: float64(1), int64(4), object(8)
memory usage: 1.4+ MB
None
Количество дубликатов: 0


* Team - команда
* Season - сезон
* Player - Имя игрока
* Player_number - игровой номер
* Position - игровое амплуа, возможные значения:
    * G - голкипер
    * D - защитник
    * RW - правый вингер
    * LW - левый вингер
    * C - центр-форвард
    * F - форвард
    * W - вингер
    * сочетания через /
* Captain - статус игрока:
    * C - капитан
    * A - ассистент
* Born - год рождения
* Birthplace - место рождения
* Age - возраст на момент парсинга, 5 jun 2023
* Height - рост в см
* Weight - вес в кг
* Stick - хват клюшки
* Player_link - ссылка на страницу игрока, уникальное поле

#### Информация о переходах игроков

In [ ]:
try:
    transfers = data_read_exam('D:/jn/Masterskaya/Lemtyugov_number/transfers.csv')
except:
    transfers = data_read_exam('https://raw.githubusercontent.com/CurasaoRG/hockey_project/main/transfers.csv')

Date           Player  \
0  05/06/2023      Stefan Warg   
1  05/06/2023  Patrik Romancik   
2  05/06/2023     Paul Stanley   
3  05/06/2023   Marcus Maynard   
4  05/06/2023       Sam Hewitt   

                                         Player_link        From_team  \
0  https://www.eliteprospects.com/player/6870/ste...  HC Sparta Praha   
1  https://www.eliteprospects.com/player/102395/p...      Vlci Zilina   
2  https://www.eliteprospects.com/player/119679/p...  Solihull Barons   
3  https://www.eliteprospects.com/player/122841/m...  Solihull Barons   
4  https://www.eliteprospects.com/player/156284/s...  Solihull Barons   

                                      From_team_link     To_team  \
0  https://www.eliteprospects.com/team/164/hc-spa...     Unknown   
1  https://www.eliteprospects.com/team/1162/vlci-...  VHK Vsetín   
2  https://www.eliteprospects.com/team/1525/solih...     Retired   
3  https://www.eliteprospects.com/team/1525/solih...     Retired   
4  https://www.eliteprospects.com/team/1525/solih...     Retired   

                                        To_team_link  
0                                                NaN  
1  https://www.eliteprospects.com/team/5337/vhk-v...  
2                                                NaN  
3                                                NaN  
4                                                NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167125 entries, 0 to 167124
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype 
---  ------          --------------   ----- 
 0   Date            167125 non-null  object
 1   Player          167125 non-null  object
 2   Player_link     167125 non-null  object
 3   From_team       167125 non-null  object
 4   From_team_link  158148 non-null  object
 5   To_team         167125 non-null  object
 6   To_team_link    156866 non-null  object
dtypes: object(7)
memory usage: 8.9+ MB
None
Количество дубликатов: 7


* Date - дата перехода
* Player - имя игрока
* Player_link - ссылка на страницу игрока
* From_team - старая команда
* From_team_link - ссылка на старую команду
* To_team - новая команда
* To_team_link - ссылка на новую команду

#### Персональные данные

In [ ]:
try:
    personal_data = data_read_exam('D:/jn/Masterskaya/Lemtyugov_number/personal_data.csv')
except:
    personal_data = data_read_exam('https://raw.githubusercontent.com/CurasaoRG/hockey_project/main/players_personal_data.csv')

Player_name        Date_of_Birth Position Age  \
0          Sergei Belov  1982-09-27 00:00:00        G  40   
1       Rafael Khakimov  1990-04-06 00:00:00        G  33   
2         Vadim Tarasov  1976-12-31 00:00:00        G  46   
3  Alexander Yeryomenko  1980-04-10 00:00:00        G  43   
4       Miroslav Blatak  1982-05-25 00:00:00        D  41   

         Place_of_Birth                                             Nation  \
0   St. Petersburg, RUS                                             Russia   
1              Ufa, RUS                                             Russia   
2  Ust-Kamenogorsk, KAZ  Russia\n    \n            / \n            Kaza...   
3           Moskva, RUS                                             Russia   
4             Zlin, CZE                                            Czechia   

  Grip               Youth_Team  Height_cm Height_ft  Weight_kg Weight_lbs  \
0    L       SKA St. Petersburg        180     5'11"         78    172 lbs   
1    L       Salavat Yulaev Ufa        180     5'11"         78    172 lbs   
2    L  Torpedo Ust-Kamenogorsk        183      6'0"         84    185 lbs   
3    L            Dynamo Moskva        180     5'11"         78    172 lbs   
4    L                  HC Zlin        180     5'11"         78    172 lbs   

                                              Awards  \
0  {"2009-2010": ["Russia2 Silver Medal"], "2013-...   
1  {"2010-2011": ["MHL All-Star Game", "MHL Best ...   
2  {"1998-1999": ["RSL Best Goaltender"], "1999-2...   
3  {"2004-2005": ["RSL Champion", "World Champion...   
4  {"2001-2002": ["Czech Extraliga Bronze Medal",...   

                                         Player_link  
0  https://www.eliteprospects.com/player/19555/se...  
1  https://www.eliteprospects.com/player/47547/ra...  
2  https://www.eliteprospects.com/player/11990/va...  
3  https://www.eliteprospects.com/player/12286/al...  
4  https://www.eliteprospects.com/player/8421/mir...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3599 entries, 0 to 3598
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Player_name     3599 non-null   object
 1   Date_of_Birth   3599 non-null   object
 2   Position        3599 non-null   object
 3   Age             3599 non-null   object
 4   Place_of_Birth  3599 non-null   object
 5   Nation          3599 non-null   object
 6   Grip            3599 non-null   object
 7   Youth_Team      3599 non-null   object
 8   Height_cm       3599 non-null   int64 
 9   Height_ft       3599 non-null   object
 10  Weight_kg       3599 non-null   int64 
 11  Weight_lbs      3599 non-null   object
 12  Awards          3599 non-null   object
 13  Player_link     3599 non-null   object
dtypes: int64(2), object(12)
memory usage: 393.8+ KB
None
Количество дубликатов: 0


* Player_name - имя игрока
* Date_of_Birth - полная дата рождения
* Position - игровое амплуа, значения как в players_data
* Age - полных лет на момент выборки, 14 jun 23
* Place_of_Birth - место рождения, через запятую трёхбуквенное обозначение страны
* Nation - гражданство, если несколько, то перечислены через /
* Grip - хват клюшки
* Youth_Team - молодежная команда, в которой игрок начинал карьеру
* Height_cm - рост в см
* Height_ft - рост в футах
* Weight_kg - вес в кг
* Weight_lbs - вес в фунтах
* Awards - список наград по сезонам в формате JSON
* Player_link - ссылка на страницу игрока, уникальное поле

#### Статистика игроков

In [ ]:
try:
    players_stats = data_read_exam('D:/jn/Masterskaya/Lemtyugov_number/players_stats.csv', index_col=True)
except:
    players_stats = data_read_exam('https://raw.githubusercontent.com/CurasaoRG/hockey_project/main/players_stats.csv', index_col=True)

Player_name   Season                  Team   League  \
0  Sergei Belov  2000-01      SKASt.Petersburg   Russia   
1  Sergei Belov  2000-01    SKASt.Petersburg-2  Russia3   
2  Sergei Belov  2001-02      SKASt.Petersburg   Russia   
3  Sergei Belov  2001-02    SKASt.Petersburg-2  Russia3   
4  Sergei Belov  2001-02  SpartakSt.Petersburg  Russia2   

                                         Player_link  Regular_Games_Played  \
0  https://www.eliteprospects.com/player/19555/se...                   1.0   
1  https://www.eliteprospects.com/player/19555/se...                  25.0   
2  https://www.eliteprospects.com/player/19555/se...                   1.0   
3  https://www.eliteprospects.com/player/19555/se...                  25.0   
4  https://www.eliteprospects.com/player/19555/se...                   7.0   

   Regular_Goals  Regular_Assists  Regular_Total_Points  \
0            NaN              NaN                   NaN   
1            NaN              NaN                   NaN   
2            NaN              NaN                   NaN   
3            NaN              NaN                   NaN   
4            NaN              NaN                   NaN   

   Regular_Penalty_Minutes  ...  Postseason_Penalty_Minutes  \
0                      NaN  ...                         NaN   
1                      NaN  ...                         NaN   
2                      NaN  ...                         NaN   
3                      NaN  ...                         NaN   
4                      NaN  ...                         NaN   

   Postseason_Plus_Minus  Postseason_Games_Dressed  Postseason_GAA  \
0                    NaN                       NaN             NaN   
1                    NaN                       NaN             NaN   
2                    NaN                       NaN             NaN   
3                    NaN                       NaN             NaN   
4                    NaN                       NaN             NaN   

   Postseason_Saves_Percentage  Postseason_Goals_Against  Postseason_Saves  \
0                          NaN                       NaN               NaN   
1                          NaN                       NaN               NaN   
2                          NaN                       NaN               NaN   
3                          NaN                       NaN               NaN   
4                          NaN                       NaN               NaN   

  Postseason_Shutouts  Postseason_WLT  Postseason_TOI  
0                 NaN             NaN             NaN  
1                 NaN             NaN             NaN  
2                 NaN             NaN             NaN  
3                 NaN             NaN             NaN  
4                 NaN             NaN             NaN  

[5 rows x 33 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 116669 entries, 0 to 116915
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   Player_name                  116669 non-null  object 
 1   Season                       116669 non-null  object 
 2   Team                         116669 non-null  object 
 3   League                       116384 non-null  object 
 4   Player_link                  116669 non-null  object 
 5   Regular_Games_Played         112832 non-null  float64
 6   Regular_Goals                99535 non-null   float64
 7   Regular_Assists              99475 non-null   float64
 8   Regular_Total_Points         99474 non-null   float64
 9   Regular_Penalty_Minutes      98700 non-null   float64
 10  Regular_Plus_Minus           75753 non-null   float64
 11  Regular_Games_Dressed        5959 non-null    float64
 12  Regular_GAA                  11179 non-null   float64
 13 

* Player_name - имя игрока
* Season - сезон
* Team - команда
* League - лига
* Player_link - ссылка на страницу игрока
* `Regular_Games_Played` - количество сыгранных игр (Регулярный сезон)
    * Показатели только для полевых игроков (регулярный сезон)
        * Regular_Goals - количество голов
        * Regular_Assists - количество передач
        * Regular_Total_Points - общее количество очков
        * Regular_Penalty_Minutes - количество штрафных минут
        * Regular_Plus_Minus - показатель плюс-минус
    * Показатели только для вратарей (регулярный сезон)
        * Regular_Games_Dressed - количество игр, на которых вратарь был заявлен на игру, но сидел в запасе
        * Regular_GAA - коэффициент надёжности, показывает, сколько в среднем шайб пропускает вратарь за 60 минут игрового времени
        * Regular_Saves_Percentage - процент отраженных бросков
        * Regular_Goals_Against - количество пропущенных голов
        * Regular_Saves- количество сейвов
        * Regular_Shutouts - количество игр на ноль
        * Regular_WLT - win-lose-tie, соотношение выигранных, проигранных и ничейных (в основное время) игр
        * Regular_TOI - время на льду
* `Postseason_Games_Played` (gлей-офф)
    * Показатели только для полевых игроков (плей-офф)
        * Postseason_Goals
        * Postseason_Assists
        * Postseason_Total_Points
        * Postseason_Penalty_Minutes
        * Postseason_Plus_Minus
    * Показатели только для вратарей (плей-офф)
        * Postseason_Games_Dressed
        * Postseason_GAA
        * Postseason_Saves_Percentage
        * Postseason_Goals_Against
        * Postseason_Saves
        * Postseason_Shutouts
        * Postseason_WLT
        * Postseason_TOI

#### Вывод
Данные довольно чистые. Только в таблице с переходами имеется незначительное количество дубликатов, удалим их на этапе предобработки.

## Предобработка данных.



#### players_data - информацией об игроках.

In [ ]:
players_data.head()

Team     Season                Player  Player_number  \
0  Salavat Yulaev Ufa  2008-2009          Sergei Belov             31   
1  Salavat Yulaev Ufa  2008-2009       Rafael Khakimov             31   
2  Salavat Yulaev Ufa  2008-2009         Vadim Tarasov              1   
3  Salavat Yulaev Ufa  2008-2009  Alexander Yeryomenko             30   
4  Salavat Yulaev Ufa  2008-2009       Miroslav Blatak             23   

  Position Captain  Born            Birthplace   Age  Height  Weight Stick  \
0        G     NaN  1982   St. Petersburg, RUS  40.0     180      78     L   
1        G     NaN  1990              Ufa, RUS  33.0     180      78     L   
2        G     NaN  1976  Ust-Kamenogorsk, KAZ  46.0     183      84     L   
3        G     NaN  1980           Moskva, RUS  43.0     180      78     L   
4        D     NaN  1982             Zlin, CZE  41.0     180      78     L   

                                         Player_link  
0  https://www.eliteprospects.com/player/19555/se...  
1  https://www.eliteprospects.com/player/47547/ra...  
2  https://www.eliteprospects.com/player/11990/va...  
3  https://www.eliteprospects.com/player/12286/al...  
4  https://www.eliteprospects.com/player/8421/mir...

Добавим в датафрейм с информацией об игроках колонки с датами начала и окончания сезона в формате `datetime`.

In [ ]:
# Создадим словарь с датами начала и окончания сезонов КХЛ.
season_dates_khl = {
    '2008-2009': (datetime(2008, 9, 2), datetime(2009, 4, 12)),
    '2009-2010': (datetime(2009, 9, 10), datetime(2010, 4, 22)),
    '2010-2011': (datetime(2010, 9, 8), datetime(2011, 4, 20)),
    '2011-2012': (datetime(2011, 9, 7), datetime(2012, 4, 29)),
    '2012-2013': (datetime(2012, 9, 4), datetime(2013, 4, 17)),
    '2013-2014': (datetime(2013, 9, 4), datetime(2014, 4, 30)),
    '2014-2015': (datetime(2014, 8, 25), datetime(2015, 4, 30)),
    '2015-2016': (datetime(2015, 8, 24), datetime(2016, 4, 19)),
    '2016-2017': (datetime(2016, 8, 22), datetime(2017, 4, 16)),
    '2017-2018': (datetime(2017, 8, 21), datetime(2018, 4, 19)),
    '2018-2019': (datetime(2018, 9, 1), datetime(2019, 4, 19)),
    '2019-2020': (datetime(2019, 9, 1), datetime(2020, 3, 12)),
    '2020-2021': (datetime(2020, 9, 2), datetime(2021, 5, 7)),
    '2021-2022': (datetime(2021, 9, 1), datetime(2022, 4, 30)),
    '2022-2023': (datetime(2022, 9, 1), datetime(2023, 4, 29))
}

In [ ]:
# Добавим столбец с началом сезона по значению из колонки 'Season'
players_data['Season_on'] = players_data['Season'].map(season_dates_khl).str[0]
players_data['Season_on'] = pd.to_datetime(players_data['Season_on'], format='%Y-%m-%dT')
# Изменим формат даты, оставим только год, месяц, день

In [ ]:
# Добавим столбец с окончанием сезона по значению из колонки 'Season'
players_data['Season_off'] = players_data['Season'].map(season_dates_khl).str[1]
players_data['Season_off'] = pd.to_datetime(players_data['Season_off'], format='%Y-%m-%dT')
# Изменим формат даты, оставим только год, месяц, день

Выделим id из личных ссылок игроков.

In [ ]:
players_data['id'] = players_data['Player_link'].str.extract(r'player/(\d+)').astype(int)

Удалим лишние столбцы.

In [ ]:
players_data = players_data.drop(['Player_link','Player_number', 'Position','Captain','Born','Birthplace','Age','Height','Weight','Stick'], axis=1)

Посмотрим на измененный датафрейм и информацию о нем.

In [ ]:
players_data.head()

Team     Season                Player  Season_on Season_off  \
0  Salavat Yulaev Ufa  2008-2009          Sergei Belov 2008-09-02 2009-04-12   
1  Salavat Yulaev Ufa  2008-2009       Rafael Khakimov 2008-09-02 2009-04-12   
2  Salavat Yulaev Ufa  2008-2009         Vadim Tarasov 2008-09-02 2009-04-12   
3  Salavat Yulaev Ufa  2008-2009  Alexander Yeryomenko 2008-09-02 2009-04-12   
4  Salavat Yulaev Ufa  2008-2009       Miroslav Blatak 2008-09-02 2009-04-12   

      id  
0  19555  
1  47547  
2  11990  
3  12286  
4   8421

In [ ]:
players_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14332 entries, 0 to 14331
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Team        14332 non-null  object        
 1   Season      14332 non-null  object        
 2   Player      14332 non-null  object        
 3   Season_on   14332 non-null  datetime64[ns]
 4   Season_off  14332 non-null  datetime64[ns]
 5   id          14332 non-null  int64         
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 671.9+ KB


Создадим словарь, где id - это ключ игрока, а имя и фамилия - это значение словаря.

In [ ]:
id_dic = players_data[['id', 'Player']].to_dict('records')
players_dict = {}
for i in id_dic:
  for k, v in i.items():
    players_dict.update({i['id']: i['Player']})

Выделим id Николая Лемтюгова.

In [ ]:
search_name = 'Nikolai Lemtyugov'
[id for id, name in players_dict.items() if name == search_name]

[9263]

Создадим список уникальных id игроков.

In [ ]:
id_unique_list = players_data['id'].unique().tolist()

Посмотрим количество уникальных игроков в КХЛ.

In [ ]:
len(id_unique_list)

3599

Создадим список команд КХЛ.

In [ ]:
teams = players_data['Team'].unique().tolist()

Посмотрим количество команд в КХЛ.

In [ ]:
len(teams)

40

#### transfers - информацией о переходах игроков.

In [ ]:
transfers.head()

Date           Player  \
0  05/06/2023      Stefan Warg   
1  05/06/2023  Patrik Romancik   
2  05/06/2023     Paul Stanley   
3  05/06/2023   Marcus Maynard   
4  05/06/2023       Sam Hewitt   

                                         Player_link        From_team  \
0  https://www.eliteprospects.com/player/6870/ste...  HC Sparta Praha   
1  https://www.eliteprospects.com/player/102395/p...      Vlci Zilina   
2  https://www.eliteprospects.com/player/119679/p...  Solihull Barons   
3  https://www.eliteprospects.com/player/122841/m...  Solihull Barons   
4  https://www.eliteprospects.com/player/156284/s...  Solihull Barons   

                                      From_team_link     To_team  \
0  https://www.eliteprospects.com/team/164/hc-spa...     Unknown   
1  https://www.eliteprospects.com/team/1162/vlci-...  VHK Vsetín   
2  https://www.eliteprospects.com/team/1525/solih...     Retired   
3  https://www.eliteprospects.com/team/1525/solih...     Retired   
4  https://www.eliteprospects.com/team/1525/solih...     Retired   

                                        To_team_link  
0                                                NaN  
1  https://www.eliteprospects.com/team/5337/vhk-v...  
2                                                NaN  
3                                                NaN  
4                                                NaN

Удалим дубликаты

In [ ]:
transfers = transfers.drop_duplicates().reset_index(drop=True)

Выделим id из личных ссылок игроков.

In [ ]:
transfers['id'] = transfers['Player_link'].str.extract(r'player/(\d+)').astype(int)

Преобразуем значения в колонке с датой в формат `datetime`.

In [ ]:
transfers['Date'] = pd.to_datetime(transfers['Date'], dayfirst = True)

Добавим колонку со значением года, выделенной из даты перехода.

In [ ]:
transfers['Year'] = (pd.DatetimeIndex(transfers['Date']).year)

Создадим функции для определения сезона по дате перехода, которые создают две колонки со значениями сезонов для уходящих и приходящих игроков. В дальнейшем по этим колонкам будем соединять датафрейм с информацией о переходах игроков с датафреймом с информацией о переходах по колонке 'Season'.

In [ ]:
def season_from (row):
    if row['Date'] < datetime(row['Year'], 8, 21):
        return f'{int(row.Year)-1}-{row.Year}'
    return f'{row.Year}-{int(row.Year)+1}'

transfers['Season_from'] = transfers.apply(season_from, axis=1)

In [ ]:
def season_to (row):
    if row['Date'] > datetime(row['Year'], 4, 30):
        return f'{row.Year}-{int(row.Year)+1}'
    return f'{int(row.Year)-1}-{row.Year}'

transfers['Season_to'] = transfers.apply(season_to, axis=1)

Удалим лишнее колонки.

In [ ]:
transfers = transfers.drop(['Player_link','From_team_link','To_team_link','Year'], axis=1)

In [ ]:
transfers.head()

Date           Player        From_team     To_team      id  \
0 2023-06-05      Stefan Warg  HC Sparta Praha     Unknown    6870   
1 2023-06-05  Patrik Romancik      Vlci Zilina  VHK Vsetín  102395   
2 2023-06-05     Paul Stanley  Solihull Barons     Retired  119679   
3 2023-06-05   Marcus Maynard  Solihull Barons     Retired  122841   
4 2023-06-05       Sam Hewitt  Solihull Barons     Retired  156284   

  Season_from  Season_to  
0   2022-2023  2023-2024  
1   2022-2023  2023-2024  
2   2022-2023  2023-2024  
3   2022-2023  2023-2024  
4   2022-2023  2023-2024

Отфильтруем датафрейм с информацией о переходах игроков по уникальным id игроков КХЛ и по переходам игроков из команды или в команду по списку уникальных команд КХЛ.

In [ ]:
transfers_clean = transfers[
    (transfers['id'].isin(id_unique_list) == True) &
    (transfers['From_team'].isin(teams) == True) |
    (transfers['To_team'].isin(teams) == True)
    ]

Посмотрим количество id игроков в отфильтрованном датафрейме с информацией о переходах игроков.

In [ ]:
len(transfers_clean['id'].unique())

3441

Для 158 игроков отсутствует информация о трансферах.

Сбросим индексы в отфильтрованном датафрейме.

In [ ]:
transfers_clean.reset_index(drop=True, inplace=True)

### Объединение датафреймов.

In [ ]:
players_data.head()

Team     Season                Player  Season_on Season_off  \
0  Salavat Yulaev Ufa  2008-2009          Sergei Belov 2008-09-02 2009-04-12   
1  Salavat Yulaev Ufa  2008-2009       Rafael Khakimov 2008-09-02 2009-04-12   
2  Salavat Yulaev Ufa  2008-2009         Vadim Tarasov 2008-09-02 2009-04-12   
3  Salavat Yulaev Ufa  2008-2009  Alexander Yeryomenko 2008-09-02 2009-04-12   
4  Salavat Yulaev Ufa  2008-2009       Miroslav Blatak 2008-09-02 2009-04-12   

      id  
0  19555  
1  47547  
2  11990  
3  12286  
4   8421

In [ ]:
transfers_clean.head()

Date             Player               From_team  \
0 2023-06-05      Vadim Nikitin          Lada Togliatti   
1 2023-06-05   Alexander Gordin                HK Sochi   
2 2023-06-05    Nikolai Smirnov          Yunison-Moskva   
3 2023-06-05  Danila Kvartalnov          Spartak Moskva   
4 2023-06-05   Nikolay Goldobin  Metallurg Magnitogorsk   

                  To_team      id Season_from  Season_to  
0     Admiral Vladivostok  273056   2022-2023  2023-2024  
1              Ryazan-VDV  514678   2022-2023  2023-2024  
2   Yugra Khanty-Mansiysk  588579   2022-2023  2023-2024  
3  Metallurg Magnitogorsk  265483   2022-2023  2023-2024  
4          Spartak Moskva  160550   2022-2023  2023-2024

#### Исходящие трансферы.
Создадим датафрейм объединяющий информацию об игроках и их уходах из команд.

In [ ]:
players_transfers_from = players_data.merge(transfers_clean, how='left', left_on=['id','Season','Team'], right_on= ['id','Season_from','From_team'])

Переименуем колонку с датой трансфера игрока, на дату ухода из команды.

In [ ]:
players_transfers_from.rename(columns = {'Date':'Date_end'}, inplace = True )

#### Входящие трансферы.
Создадим датафрейм объединяющий информацию об игроках и их переходах в команды.

In [ ]:
players_transfers_to = players_data.merge(transfers_clean, how='left', left_on=['id','Season','Team'], right_on= ['id','Season_to','To_team'])

Переименуем колонку с датой трансфера игрока, на дату перехода игрока в команду.

In [ ]:
players_transfers_to.rename(columns = {'Date':'Date_start'}, inplace = True )

#### Общий датафрейм.

In [ ]:
players_transfers_to.head()

Team     Season              Player_x  Season_on Season_off  \
0  Salavat Yulaev Ufa  2008-2009          Sergei Belov 2008-09-02 2009-04-12   
1  Salavat Yulaev Ufa  2008-2009       Rafael Khakimov 2008-09-02 2009-04-12   
2  Salavat Yulaev Ufa  2008-2009         Vadim Tarasov 2008-09-02 2009-04-12   
3  Salavat Yulaev Ufa  2008-2009  Alexander Yeryomenko 2008-09-02 2009-04-12   
4  Salavat Yulaev Ufa  2008-2009       Miroslav Blatak 2008-09-02 2009-04-12   

      id Date_start Player_y From_team To_team Season_from Season_to  
0  19555        NaT      NaN       NaN     NaN         NaN       NaN  
1  47547        NaT      NaN       NaN     NaN         NaN       NaN  
2  11990        NaT      NaN       NaN     NaN         NaN       NaN  
3  12286        NaT      NaN       NaN     NaN         NaN       NaN  
4   8421        NaT      NaN       NaN     NaN         NaN       NaN

In [ ]:
players_transfers_from.head()

Team     Season              Player_x  Season_on Season_off  \
0  Salavat Yulaev Ufa  2008-2009          Sergei Belov 2008-09-02 2009-04-12   
1  Salavat Yulaev Ufa  2008-2009       Rafael Khakimov 2008-09-02 2009-04-12   
2  Salavat Yulaev Ufa  2008-2009         Vadim Tarasov 2008-09-02 2009-04-12   
3  Salavat Yulaev Ufa  2008-2009  Alexander Yeryomenko 2008-09-02 2009-04-12   
4  Salavat Yulaev Ufa  2008-2009       Miroslav Blatak 2008-09-02 2009-04-12   

      id   Date_end       Player_y           From_team  \
0  19555        NaT            NaN                 NaN   
1  47547        NaT            NaN                 NaN   
2  11990 2009-08-03  Vadim Tarasov  Salavat Yulaev Ufa   
3  12286        NaT            NaN                 NaN   
4   8421        NaT            NaN                 NaN   

                   To_team Season_from  Season_to  
0                      NaN         NaN        NaN  
1                      NaN         NaN        NaN  
2  Neftekhimik Nizhnekamsk   2008-2009  2009-2010  
3                      NaN         NaN        NaN  
4                      NaN         NaN        NaN

Объединим датафреймы исходящих и входящих трансферов.

In [ ]:
merged = players_transfers_from.merge(players_transfers_to[['Team', 'Season', 'id','Date_start']], how='left', on=['Team', 'Season', 'id'])

In [ ]:
merged.head()

Team     Season              Player_x  Season_on Season_off  \
0  Salavat Yulaev Ufa  2008-2009          Sergei Belov 2008-09-02 2009-04-12   
1  Salavat Yulaev Ufa  2008-2009       Rafael Khakimov 2008-09-02 2009-04-12   
2  Salavat Yulaev Ufa  2008-2009         Vadim Tarasov 2008-09-02 2009-04-12   
3  Salavat Yulaev Ufa  2008-2009  Alexander Yeryomenko 2008-09-02 2009-04-12   
4  Salavat Yulaev Ufa  2008-2009       Miroslav Blatak 2008-09-02 2009-04-12   

      id   Date_end       Player_y           From_team  \
0  19555        NaT            NaN                 NaN   
1  47547        NaT            NaN                 NaN   
2  11990 2009-08-03  Vadim Tarasov  Salavat Yulaev Ufa   
3  12286        NaT            NaN                 NaN   
4   8421        NaT            NaN                 NaN   

                   To_team Season_from  Season_to Date_start  
0                      NaN         NaN        NaN        NaT  
1                      NaN         NaN        NaN        NaT  
2  Neftekhimik Nizhnekamsk   2008-2009  2009-2010        NaT  
3                      NaN         NaN        NaN        NaT  
4                      NaN         NaN        NaN        NaT

Заменим пропуски в колонке даты перехода игрока в команду, датой начала сезона.

In [ ]:
merged['Date_start'] = merged['Date_start'].fillna(merged['Season_on'])

Заменим пропуски в колонке даты ухода игрока из команды, датой окончания сезона.

In [ ]:
merged['Date_end'] = merged['Date_end'].fillna(merged['Season_off'])

Проверим число уникальных игроков КХЛ в конечном датафрейме.

In [ ]:
merged.id.nunique()

3599

Всё в порядке никого не потеряли)

Удалим лишние колонки.

In [ ]:
merged = merged.drop(['Season_on','Season_off','Player_y','Season_from','Season_to','From_team'], axis=1)

Изменим порядок колонок в датафрейме для легкости восприятия.

In [ ]:
merged = merged[['Team','Season','id','Player_x','Date_start','Date_end','To_team']]

Проверим наличие дубликатав.

In [ ]:
merged[merged.duplicated()== True]

Team     Season      id        Player_x Date_start  \
9509  Severstal Cherepovets  2017-2018   79504  Matej Stransky 2017-06-19   
9810         Lada Togliatti  2017-2018  225383   Yegor Babenko 2017-07-09   

       Date_end To_team  
9509 2018-04-19     NaN  
9810 2018-04-19     NaN

Удалим дубликаты.

In [ ]:
merged = merged.drop_duplicates().reset_index(drop=True)

In [ ]:
merged

Team     Season      id              Player_x Date_start  \
0      Salavat Yulaev Ufa  2008-2009   19555          Sergei Belov 2008-09-02   
1      Salavat Yulaev Ufa  2008-2009   47547       Rafael Khakimov 2008-09-02   
2      Salavat Yulaev Ufa  2008-2009   11990         Vadim Tarasov 2008-09-02   
3      Salavat Yulaev Ufa  2008-2009   12286  Alexander Yeryomenko 2008-09-02   
4      Salavat Yulaev Ufa  2008-2009    8421       Miroslav Blatak 2008-09-02   
...                   ...        ...     ...                   ...        ...   
14498            HK Sochi  2022-2023   75331      Nikita Tochitsky 2022-09-01   
14499            HK Sochi  2022-2023  266824        Artur Tyanulin 2022-05-02   
14500            HK Sochi  2022-2023  561884          Dmitri Utkin 2022-09-01   
14501            HK Sochi  2022-2023  652831        Tigran Yarulin 2022-09-01   
14502            HK Sochi  2022-2023  396918     Dmitri Zavgorodny 2022-06-12   

        Date_end                  To_team  
0     2009-04-12                      NaN  
1     2009-04-12                      NaN  
2     2009-08-03  Neftekhimik Nizhnekamsk  
3     2009-04-12                      NaN  
4     2009-04-12                      NaN  
...          ...                      ...  
14498 2023-04-30                  Unknown  
14499 2023-04-29                      NaN  
14500 2023-04-29                      NaN  
14501 2023-04-29                      NaN  
14502 2023-04-29                      NaN  

[14503 rows x 7 columns]

Проверим общий датафрейм на примере Николая Лемтюгова.
Выведем все записи с Лемтюговым из исходного датафрема с информацией об игроках и из общего датафрема.

In [ ]:
players_data[players_data['id'] == 9263]

Team     Season             Player  Season_on  \
586     Severstal Cherepovets  2008-2009  Nikolai Lemtyugov 2008-09-02   
1120            Ak Bars Kazan  2009-2010  Nikolai Lemtyugov 2009-09-10   
1395    Severstal Cherepovets  2009-2010  Nikolai Lemtyugov 2009-09-10   
1840            Ak Bars Kazan  2010-2011  Nikolai Lemtyugov 2010-09-08   
2674   Metallurg Magnitogorsk  2011-2012  Nikolai Lemtyugov 2011-09-07   
2744            Ak Bars Kazan  2011-2012  Nikolai Lemtyugov 2011-09-07   
3123  Neftekhimik Nizhnekamsk  2011-2012  Nikolai Lemtyugov 2011-09-07   
3540      Traktor Chelyabinsk  2012-2013  Nikolai Lemtyugov 2012-09-04   
4002         Atlant Mytishchi  2012-2013  Nikolai Lemtyugov 2012-09-04   
4847        Sibir Novosibirsk  2013-2014  Nikolai Lemtyugov 2013-09-04   
5243           Spartak Moskva  2013-2014  Nikolai Lemtyugov 2013-09-04   
5742            Avangard Omsk  2014-2015  Nikolai Lemtyugov 2014-08-25   
6400    Yugra Khanty-Mansiysk  2014-2015  Nikolai Lemtyugov 2014-08-25   
6694            Avangard Omsk  2015-2016  Nikolai Lemtyugov 2015-08-24   
7807            Avangard Omsk  2016-2017  Nikolai Lemtyugov 2016-08-22   
9183            Avangard Omsk  2017-2018  Nikolai Lemtyugov 2017-08-21   

     Season_off    id  
586  2009-04-12  9263  
1120 2010-04-22  9263  
1395 2010-04-22  9263  
1840 2011-04-20  9263  
2674 2012-04-29  9263  
2744 2012-04-29  9263  
3123 2012-04-29  9263  
3540 2013-04-17  9263  
4002 2013-04-17  9263  
4847 2014-04-30  9263  
5243 2014-04-30  9263  
5742 2015-04-30  9263  
6400 2015-04-30  9263  
6694 2016-04-19  9263  
7807 2017-04-16  9263  
9183 2018-04-19  9263

In [ ]:
merged[merged['id'] == 9263].sort_values(by = 'Date_start')

Team     Season    id           Player_x Date_start  \
587     Severstal Cherepovets  2008-2009  9263  Nikolai Lemtyugov 2008-09-02   
1397    Severstal Cherepovets  2009-2010  9263  Nikolai Lemtyugov 2009-09-10   
1122            Ak Bars Kazan  2009-2010  9263  Nikolai Lemtyugov 2010-01-14   
1845            Ak Bars Kazan  2010-2011  9263  Nikolai Lemtyugov 2010-09-08   
2751            Ak Bars Kazan  2011-2012  9263  Nikolai Lemtyugov 2011-09-07   
2681   Metallurg Magnitogorsk  2011-2012  9263  Nikolai Lemtyugov 2011-11-04   
3134  Neftekhimik Nizhnekamsk  2011-2012  9263  Nikolai Lemtyugov 2011-12-30   
4024         Atlant Mytishchi  2012-2013  9263  Nikolai Lemtyugov 2012-05-29   
3555      Traktor Chelyabinsk  2012-2013  9263  Nikolai Lemtyugov 2012-12-29   
4883        Sibir Novosibirsk  2013-2014  9263  Nikolai Lemtyugov 2013-05-22   
5290           Spartak Moskva  2013-2014  9263  Nikolai Lemtyugov 2013-12-09   
5800            Avangard Omsk  2014-2015  9263  Nikolai Lemtyugov 2014-07-11   
6469    Yugra Khanty-Mansiysk  2014-2015  9263  Nikolai Lemtyugov 2014-12-25   
6768            Avangard Omsk  2015-2016  9263  Nikolai Lemtyugov 2015-07-10   
7895            Avangard Omsk  2016-2017  9263  Nikolai Lemtyugov 2016-08-22   
9301            Avangard Omsk  2017-2018  9263  Nikolai Lemtyugov 2017-08-21   

       Date_end                  To_team  
587  2009-04-12                      NaN  
1397 2010-01-14            Ak Bars Kazan  
1122 2010-04-22                      NaN  
1845 2011-04-20                      NaN  
2751 2011-11-04   Metallurg Magnitogorsk  
2681 2011-12-30  Neftekhimik Nizhnekamsk  
3134 2012-05-29         Atlant Mytishchi  
4024 2012-12-29      Traktor Chelyabinsk  
3555 2013-05-22        Sibir Novosibirsk  
4883 2013-12-09           Spartak Moskva  
5290 2014-07-11            Avangard Omsk  
5800 2014-12-25    Yugra Khanty-Mansiysk  
6469 2015-07-10            Avangard Omsk  
6768 2016-04-19                      NaN  
7895 2017-04-16                      NaN  
9301 2018-04-19                      NaN

Переходы выглядят логичными и последовательными, дубликатов нет.

Посмотрим особенности общего датафрейма.

In [ ]:
ProfileReport(merged)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

* Отметим:
    * Большего всего строчек относится к командам (топ-5): Нефтехимик - 614, ЦСКА - 608, Северсталь - 602, СКА - 597, Амур - 590
    * Количество id игроков - 3599, количество уникальных имен и фамилий игроков - 3561, что свидетельствует о тезках и однофамильцах.
    * В колонке 'To_team' 66% пропусков, это означает, что в конкретном сезоне игрок не переходил в другие команды.

# Во время выполнения проекта стали доступны датасеты из другого источника, возможно более подходящие для нашего исследования, рассмотрим их ниже.

## Изучение и обработка датафрема на основе данных с сайта https://en.khl.ru/


### players - информация о периодах нахождения игроков в командах.

Создадим функцию для загрузки датафреймов и выводу информации по ним.

In [ ]:
def data_read_exam(file_path, parse_dates=False):
    """
    input:        file_path [object] - путь к файлу
                  parse_dates - параметр для преобразования даты

    output:       data [DataFrame] - таблица данных
    description:  функция загружает таблицу функцией read_csv, преобразовыввает даты в datetime,
                  выводит первые 5 строк на экран, выводит информацию о данных методом info(), считает количество дубликатов
    """
    # читаем данные из .csv файла с помощью метода read_csv()
    if parse_dates == True:
        data = pd.read_csv(file_path, parse_dates=['start_date','end_date'], dayfirst=True) # преобразуем даты
    else:
        data = pd.read_csv(file_path)
    display(data.head())
    print(data.info())
    print('Количество дубликатов:', sum(data.duplicated()))
    return data

In [ ]:
players = data_read_exam('https://docs.google.com/spreadsheets/d/e/2PACX-1vT3TtrPT83dPIbAEtp5tjhpHmllTxYjFhJ62lThCeI9yPMeYwMCHPq9J5uoAL-Zcx3HvxMlXEeEl8iT/pub?output=csv',
    parse_dates=True)

player_link              player  \
0  https://en.khl.ru/players/16785/?idplayer=1678...  Juhamatti Aaltonen   
1  https://en.khl.ru/players/16785/?idplayer=1678...  Juhamatti Aaltonen   
2  https://en.khl.ru/players/17585/?idplayer=1758...       Miro Aaltonen   
3  https://en.khl.ru/players/17585/?idplayer=1758...       Miro Aaltonen   
4  https://en.khl.ru/players/17585/?idplayer=1758...       Miro Aaltonen   

           team start_date   end_date  
0       Jokerit 2014-09-04 2016-03-02  
1  Metallurg Mg 2010-09-09 2012-03-22  
2        Vityaz 2021-09-02 2022-01-11  
3           SKA 2019-12-17 2021-02-27  
4        Vityaz 2016-08-27 2019-12-09

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8179 entries, 0 to 8178
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   player_link  8179 non-null   object        
 1   player       8179 non-null   object        
 2   team         8179 non-null   object        
 3   start_date   8179 non-null   datetime64[ns]
 4   end_date     8179 non-null   datetime64[ns]
dtypes: datetime64[ns](2), object(3)
memory usage: 319.6+ KB
None
Количество дубликатов: 0


* player_link - ссылка на страницу игрока, уникальное поле
* player - имя и фамилия игрока
* team - команда
* start_date - дата, когда игрок начал играть за команду
* end_date - дата, когда игрок ушел из команды

Выделим id из личных ссылок игроков.

In [ ]:
players['player_link'] = players['player_link'].str.extract(r'players/(\d+)').astype(int)

In [ ]:
players.rename(columns = {'player_link':'id'}, inplace = True)

Посмотрим особенности общего датафрейма.

In [ ]:
ProfileReport(players)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

* Отметим:
    * Большего всего строчек относится к командам (топ-5): Спартак - 370, Нефтехимик - 369, Амур - 356, Торпедо - 352, Витязь -346
    * Количество уникальных id игроков - 3720, количество уникальных имен и фамилий игроков - 3712, что свидетельствует о тезках и однофамильцах.    

Создадим словарь, где id - это ключ игрока, а имя и фамилия - это значение словаря.

In [ ]:
id_dic = players[['id', 'player']].to_dict('records')
players_dict_2 = {}
for i in id_dic:
  for k, v in i.items():
    players_dict_2.update({i['id']: i['player']})

Посмотрим id Николая Лемтюгова.

In [ ]:
search_name = 'Nikolai Lemtyugov'
[id for id, name in players_dict_2.items() if name == search_name]

[13705]

Выведем все записи по Николаю Лемтюгову.

In [ ]:
players[players['id'] == 13705].sort_values(by = 'start_date')

id             player          team start_date   end_date
3756  13705  Nikolai Lemtyugov     Severstal 2008-12-24 2010-01-12
3755  13705  Nikolai Lemtyugov       Ak Bars 2010-01-14 2011-10-28
3754  13705  Nikolai Lemtyugov  Metallurg Mg 2011-11-04 2011-12-27
3753  13705  Nikolai Lemtyugov   Neftekhimik 2012-01-05 2012-02-26
3752  13705  Nikolai Lemtyugov        Atlant 2012-09-05 2012-12-23
3751  13705  Nikolai Lemtyugov       Traktor 2013-01-04 2013-04-15
3750  13705  Nikolai Lemtyugov         Sibir 2013-09-05 2013-12-08
3749  13705  Nikolai Lemtyugov       Spartak 2013-12-13 2014-03-04
3748  13705  Nikolai Lemtyugov      Avangard 2014-09-04 2014-12-10
3747  13705  Nikolai Lemtyugov          Ugra 2014-12-30 2015-02-24
3746  13705  Nikolai Lemtyugov      Avangard 2015-08-25 2018-03-10

**Вывод**
* Хронология прибывания хоккеистов в командах соответствует ранее полученной из исходных датафреймов, но является более точной. Например, между датами ухода из команды и датами прихода в другую команду, имеется какое-то незначительное количество дней, когда игрок не числился ни в одной из команд, в общем исходном датафрейме дата трансфера являлась датой ухода из одной команды и она же являлась датой прихода в другую команду.
* Датафрейм на основе данных с сайта https://en.khl.ru/ является более точным и исключает некоторые ошибки, которые могли возникнуть из-за неполноты данных в исходных датафремах с информацией об игроках и о переходах игроков, а также из-за наличия записей о несовершенных трансферов.
* Для дальнейшего расчета числа Лемтюгова будем использовать датафреймы на основе данных с сайта https://en.khl.ru/

### stat - статистика игроков

In [ ]:
stat = pd.read_csv(
    'https://docs.google.com/spreadsheets/d/e/2PACX-1vT411kwpQk6lUrapB4bnsC1--cUkQMxWieItZ0sfIoYdmsO50Lu_hWws-r_UBfaww/pub?output=csv')

In [ ]:
display(stat.head())
print(stat.info())
print('Количество дубликатов:', sum(stat.duplicated()))

player_link               player  \
0  https://en.khl.ru/players/16785/?idplayer=1678...   Juhamatti Aaltonen   
1  https://en.khl.ru/players/17585/?idplayer=1758...        Miro Aaltonen   
2  https://en.khl.ru/players/13041/?idplayer=1304...  Ruslan Abdrakhmanov   
3  https://en.khl.ru/players/38736/?idplayer=3873...       Jindrich Abdul   
4  https://en.khl.ru/players/24998/?idplayer=2499...    Ilnur Abdulkhakov   

     position        born age  country  hight  weight  shoot   GP  ...   FOA  \
0     forward   4-июн.-85  38  Finland    184      89  right  245  ...  22.0   
1     forward   7-июн.-93  30  Finland    177      84   left  256  ...  60.0   
2     forward  25-дек.-84  38   Russia    178      77   left   10  ...   0.0   
3     forward  1-февр.-96  27  Czechia    185      85   left   12  ...   7.0   
4  goaltender  15-янв.-99  24   Russia    187      84   left    0  ...   NaN   

   TkA    W    L  SOP   GA   Sv  %Sv  GAA   SO  
0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4  NaN  0.0  0.0  0.0  0.0  0.0    -    -  0.0  

[5 rows x 49 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3717 entries, 0 to 3716
Data columns (total 49 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   player_link  3717 non-null   object 
 1   player       3717 non-null   object 
 2   position     3717 non-null   object 
 3   born         3717 non-null   object 
 4   age          3717 non-null   object 
 5   country      3717 non-null   object 
 6   hight        3717 non-null   int64  
 7   weight       3717 non-null   int64  
 8   shoot        3717 non-null   object 
 9   GP           3717 non-null   int64  
 10  G            3717 non-null   int64  
 11  Assists      3717 non-null   int64  
 12  PTS          3226 non-null   float64
 13  +/-          3226 non-null   float64
 14  +            3226 non-null   float64
 15  -            3226 non-null   float64
 16  PIM          3717 non-null   int64  
 17  ESG          3226 non-null   float64
 18  PPG          3226 non-null   float64
 19  SHG   

Преобразуем дату рождения в datetime.

In [ ]:
month = {
    'янв.': 'Jan',
    'февр.': 'Feb',
    'мар.': 'Mar',
    'апр.': 'Apr',
    'мая': 'May',
    'июн.': 'Jun',
    'июл.': 'Jul',
    'авг.': 'Aug',
    'сент.': 'Sep',
    'окт.': 'Oct',
    'нояб.': 'Nov',
    'дек.': 'Dec'
}
stat['born'] = stat['born'].replace(month, regex=True)
stat['born'] = pd.to_datetime(stat['born'], format='%d-%b-%y')

Добавим колонку с месяцем рождения.

In [ ]:
stat.insert(loc= 3 , column='month_born', value=stat['born'].dt.month)

Выделим id из личных ссылок игроков.

In [ ]:
stat['player_link'] = stat['player_link'].str.extract(r'players/(\d+)').astype(int)

In [ ]:
stat.rename(columns = {'player_link':'id'}, inplace = True)

In [ ]:
stat.head()

id               player    position  month_born       born age  country  \
0  16785   Juhamatti Aaltonen     forward           6 1985-06-04  38  Finland   
1  17585        Miro Aaltonen     forward           6 1993-06-07  30  Finland   
2  13041  Ruslan Abdrakhmanov     forward          12 1984-12-25  38   Russia   
3  38736       Jindrich Abdul     forward           2 1996-02-01  27  Czechia   
4  24998    Ilnur Abdulkhakov  goaltender           1 1999-01-15  24   Russia   

   hight  weight  shoot  ...   FOA  TkA    W    L  SOP   GA   Sv  %Sv  GAA  \
0    184      89  right  ...  22.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1    177      84   left  ...  60.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2    178      77   left  ...   0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3    185      85   left  ...   7.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
4    187      84   left  ...   NaN  NaN  0.0  0.0  0.0  0.0  0.0    -    -   

    SO  
0  NaN  
1  NaN  
2  NaN  
3  NaN  
4  0.0  

[5 rows x 50 columns]

Посмотрим id Николая Лемтюгова.

In [ ]:
search_name = 'Nikolai Lemtyugov'
[id for id, name in players_dict_2.items() if name == search_name]

[13705]

Выведем запись по Николаю Лемтюгову.

In [ ]:
stat[stat['id'] == 13705]

id             player position  month_born       born age country  \
1643  13705  Nikolai Lemtyugov  forward           1 1986-01-15  37  Russia   

      hight  weight shoot  ...   FOA  TkA   W   L  SOP  GA  Sv  %Sv  GAA  SO  
1643    184      96  left  ...  35.0  0.0 NaN NaN  NaN NaN NaN  NaN  NaN NaN  

[1 rows x 50 columns]

Предобработка выполнена. Датафрейм со статистикой игроков готов для проверке гипотез.

## Топы



### Топ-15 игроков по количеству команд за карьеру в КХЛ.

In [ ]:
num_teams = players.groupby(['id', 'player'])['team'].nunique().reset_index(
    name='num_teams').sort_values(by = 'num_teams', ascending=False)
num_teams[:15]

id                player  num_teams
47      548     Gennady Stolyarov         11
469   12990  Alexander Ryazantsev         11
636   14299        Denis Kazionov         11
532   13705     Nikolai Lemtyugov         10
504   13253  Alexander V. Rybakov         10
319    5433         Gleb Klimenko         10
24      266  Konstantin Glazachev         10
695   14551        Mikhail Anisin         10
428   10546           Yakov Rylov         10
524   13679        Mikhail Zhukov         10
838   15050        Nikita Filatov          9
209    4351       Evgeny Lapenkov          9
1113  15708      Alexander Avtsin          9
983   15323    Stanislav Bocharov          9
1659  17553          Ivan Nalimov          9

Николай Лемтюгов делит только второе место (10 команд) еще с семью игроками, первое место (11 команд) делят три игрока.

### Топ-15 игроков по количеству переходов за карьеру в КХЛ.

In [ ]:
num_transfers= players.groupby(['id', 'player'])['team'].count().reset_index(
    name='num_transfers').sort_values(by = 'num_transfers', ascending=False)
num_transfers[:15]

id                player  num_transfers
524   13679        Mikhail Zhukov             14
209    4351       Evgeny Lapenkov             14
636   14299        Denis Kazionov             13
319    5433         Gleb Klimenko             13
47      548     Gennady Stolyarov             12
35      392    Dmitry S. Vorobyov             12
103    3641          Igor Radulov             12
1659  17553          Ivan Nalimov             12
695   14551        Mikhail Anisin             11
428   10546           Yakov Rylov             11
532   13705     Nikolai Lemtyugov             11
469   12990  Alexander Ryazantsev             11
504   13253  Alexander V. Rybakov             11
790   14867     Mikhail Grigoryev             11
1370  16355      Alexei Kruchinin             11

По количеству переходов Николай Лемтюгов делит только четвертое место (11 переходов) еще с семью игроками, первое место (14 переходов) делят два игрока, второе место (13 игроков) делят два игрока, третье место (12 переходов) делят 4 игрока.

### Топ-15 команд по количеству игроков.

In [ ]:
num_players = players.groupby(['team'])['id'].count().reset_index(
    name='num_players').sort_values(by = 'num_players', ascending=False)
num_players[:15]

team  num_players
33         Spartak          370
26     Neftekhimik          369
2             Amur          356
34         Torpedo          352
37          Vityaz          346
30       Severstal          330
5     Avtomobilist          329
8        Dinamo Mn          305
7             CSKA          302
4         Avangard          300
31           Sibir          298
28             SKA          294
35         Traktor          292
9         Dinamo R          277
29  Salavat Yulaev          275

In [ ]:
team_num_players = players.groupby(['team'], as_index=False).agg(
    num_players=('id', 'count')).sort_values(by = 'num_players', ascending=False)[:15]

Спартак и Нефтехимик лидируют по количеству игроков побывавших в составах команд 370 и 369 игроков соответственно.

## Визуализизация переходов игроков между командами.

### **Sankey Chart** диаграммы

Чтобы строить sankey, у вас должна быть готова таблица с информацией по трансферам игроков - даты здесь не так важны, как сами переходы из команды в команду - т.е. эту визуализацию можем строить практически сразу.

Для построения Sankey чатра воспользуемся тьюториалом отсюда: https://habr.com/ru/articles/566568/ и документацией plotly по Sankey: https://plotly.com/python/sankey-diagram/

In [ ]:
def add_features(df):

    """Функция генерации новых столбцов для исходной таблицы

    Args:
        df (pd.DataFrame): исходная таблица.
    Returns:
        pd.DataFrame: таблица с новыми признаками.
    """

    # сортируем по id и времени
    sorted_df = df.sort_values(by=['id', 'start_date']).copy()
    # добавляем шаги событий
    sorted_df['step'] = sorted_df.groupby('id').cumcount() + 1

    # добавляем узлы-источники и целевые узлы
    # узлы-источники - это сами события
        # sorted_df['source'] = sorted_df['team']
        # не стал добавлять столбец 'source', понимая, что колонка 'team' и есть source
    # добавляем целевые узлы
    sorted_df['to_team'] = sorted_df.groupby('id')['team'].shift(-1)

    # возврат таблицы без имени событий
        #return sorted_df.drop(['team'], axis=1)
        # не стал удалять столбец'team', т.к. не стал создавать столбец 'source'
    return sorted_df

Преобразуем таблицу.

In [ ]:
players = add_features(players)
players.head()

id            player          team start_date   end_date  step  \
3886   1    Evgeny Lobanov       Torpedo 2008-11-12 2009-11-21     1   
3885   1    Evgeny Lobanov  Avtomobilist 2011-09-14 2014-09-30     2   
2000  11  Denis Grebeshkov           SKA 2010-09-09 2012-10-26     1   
1999  11  Denis Grebeshkov          Ugra 2012-11-02 2013-02-17     2   
1998  11  Denis Grebeshkov        Vityaz 2014-09-06 2015-02-24     3   

           to_team  
3886  Avtomobilist  
3885           NaN  
2000          Ugra  
1999        Vityaz  
1998           NaN

In [ ]:
def get_source_index(df, source='team'):

    """Функция генерации индексов source

    Args:
        df (pd.DataFrame): исходная таблица с признаками step, source, target.
    Returns:
        dict: словарь с индексами, именами и соответствием индексов именам source.
    """

    res_dict = {}

    count = 0
    # получаем индексы источников
    for no, step in enumerate(df['step'].unique().tolist()):
        # получаем уникальные наименования для шага
        res_dict[no+1] = {}
        res_dict[no+1]['sources'] = df[df['step'] == step][source].unique().tolist()
        res_dict[no+1]['players'] = df[df['step'] == step]['player'].unique().tolist()
        res_dict[no+1]['sources_index'] = []
        for i in range(len(res_dict[no+1]['sources'])):
            res_dict[no+1]['sources_index'].append(count)
            count += 1

    # соединим списки
    for key in res_dict:
        res_dict[key]['sources_dict'] = {}
        for name, no in zip(res_dict[key]['sources'], res_dict[key]['sources_index']):
            res_dict[key]['sources_dict'][name] = no
    return res_dict

In [ ]:
def generate_random_color():

    """Случайная генерация цветов rgba

    Args:

    Returns:
        str: Строка со сгенерированными параметрами цвета
    """

    # сгенерим значение для каждого канала
    r, g, b = np.random.randint(255, size=3)
    return f'rgba({r}, {g}, {b}, 1)'

In [ ]:
def colors_for_sources(mode, df, source='team'):

    """Генерация цветов rgba

    Args:
        mode (str): сгенерировать случайные цвета, если 'random', а если 'custom' -
                    использовать заранее подготовленные
    Returns:
        dict: словарь с цветами, соответствующими каждому индексу
    """
    # словарь, в который сложим цвета в соответствии с индексом
    colors_dict = {}

    if mode == 'random':
        # генерим случайные цвета
        for label in df[source].unique():
            r, g, b = np.random.randint(255, size=3)
            colors_dict[label] = f'rgba({r}, {g}, {b}, 1)'

    elif mode == 'custom':
        # присваиваем ранее подготовленные цвета
        colors = requests.get('https://raw.githubusercontent.com/rusantsovsv/senkey_tutorial/main/json/colors_senkey.json').json()
        for no, label in enumerate(df[source].unique()):
            colors_dict[label] = colors['custom_colors'][no]

    return colors_dict

In [ ]:
def percent_users(sources, targets, values):

    """
    Расчет уникальных id в процентах (для вывода в hover text каждого узла)

    Args:
        sources (list): список с индексами source.
        targets (list): список с индексами target.
        values (list): список с "объемами" потоков.

    Returns:
        list: список с "объемами" потоков в процентах
    """

    # объединим источники и метки и найдем пары
    zip_lists = list(zip(sources, targets, values))

    new_list = []

    # подготовим список словарь с общим объемом трафика в узлах
    unique_dict = {}

    # проходим по каждому узлу
    for source, target, value in zip_lists:
        if source not in unique_dict:
            # находим все источники и считаем общий трафик
            unique_dict[source] = 0
            for sr, tg, vl in zip_lists:
                if sr == source:
                    unique_dict[source] += vl

    # считаем проценты
    for source, target, value in zip_lists:
        new_list.append(round(100 * value / unique_dict[source], 1))

    return new_list

In [ ]:
def lists_for_plot(df, source_indexes, colors, st='step', source='team', target='to_team', frac=0):

    """
    Создаем необходимые для отрисовки диаграммы переменные списков и возвращаем
    их в виде словаря

    Args:
        source_indexes (dict): словарь с именами и индексами source.
        colors (dict): словарь с цветами source.
        frac (int): ограничение на минимальный "объем" между узлами.

    Returns:
        dict: словарь со списками, необходимыми для диаграммы.
    """

    sources = []
    targets = []
    values = []
    labels = []
    link_color = []
    link_text = []

    # проходим по каждому шагу
    for step in tqdm(sorted(df['step'].unique()), desc='Шаг'):
        if step + 1 not in source_indexes:
            continue

        # получаем индекс источника
        temp_dict_source = source_indexes[step]['sources_dict']

        # получаем индексы цели
        temp_dict_target = source_indexes[step+1]['sources_dict']

        # проходим по каждой возможной паре, считаем количество таких пар
        for s, index_source in tqdm(temp_dict_source.items()):
            for t, index_target in temp_dict_target.items():
                # делаем срез данных и считаем количество id
                temp_df = df[(df[st] == step)&(df[source] == s)&(df[target] == t)]
                value = len(temp_df)
                # проверяем минимальный объем потока и добавляем нужные данные
                if value > frac:
                    sources.append(index_source)
                    targets.append(index_target)
                    values.append(value)
                    # делаем поток прозрачным для лучшего отображения
                    link_color.append(colors[s].replace(', 1)', ', 0.2)'))

    labels = []
    colors_labels = []
    for key in source_indexes:
        for name in source_indexes[key]['sources']:
            labels.append(name)
            colors_labels.append(colors[name])

    # считаем проценты всех потоков
    perc_values = percent_users(sources, targets, values)

    # добавим значения процентов для howertext
    link_text = []
    for perc in perc_values:
        link_text.append(f"{perc}%")

    # возвратим словарь с вложенными списками
    return {'sources': sources,
            'targets': targets,
            'values': values,
            'labels': labels,
            'colors_labels': colors_labels,
            'link_color': link_color,
            'link_text': link_text}

In [ ]:
def plot_senkey_diagram(title, data_dict, width=2000, height=1000):

    """
    Функция для генерации объекта диаграммы Сенкей

    Args:
        data_dict (dict): словарь со списками данных для построения.

    Returns:
        plotly.graph_objs._figure.Figure: объект изображения.
    """

    fig = go.Figure(data=[go.Sankey(
        domain = dict(
          x = [0,1],
          y = [0,1]
        ),
        orientation = "h",
        valueformat = ".0f",
        node = dict(
          pad=50,
          thickness=15,
          line=dict(color = "black", width = 0.1),
          label=data_dict['labels'],
          color=data_dict['colors_labels'],
          #customdata=data_dict['players'],
          hovertemplate='Всего переходов у команды %{label}: %{value}<extra></extra>'
        ),
        link = dict(
#           arrowlen=15,
          source=data_dict['sources'],
          target=data_dict['targets'],
          value=data_dict['values'],
          label=data_dict['link_text'],
          color=data_dict['link_color'],
          customdata=data_dict['link_text'],
          hovertemplate='Из команды %{source.label}<br />'+
        'в команду %{target.label}<br /> перешло игроков: %{value}'+
        ', что составляет %{customdata}<br />',
      ))])
    fig.update_layout(title_text=title, font_size=10, width=width, height=height)



    # возвращаем объект диаграммы
    return fig


#### Переходы топ-20 игроков между командами КХЛ.

In [ ]:
players

id            player          team start_date   end_date  step  \
3886      1    Evgeny Lobanov       Torpedo 2008-11-12 2009-11-21     1   
3885      1    Evgeny Lobanov  Avtomobilist 2011-09-14 2014-09-30     2   
2000     11  Denis Grebeshkov           SKA 2010-09-09 2012-10-26     1   
1999     11  Denis Grebeshkov          Ugra 2012-11-02 2013-02-17     2   
1998     11  Denis Grebeshkov        Vityaz 2014-09-06 2015-02-24     3   
...     ...               ...           ...        ...        ...   ...   
1019  42245    Michael Chaput         Barys 2022-10-02 2022-12-24     1   
1361  42267         Jan Drozg          Amur 2022-11-08 2023-02-25     1   
2133  42322   Robert Hamilton       Traktor 2022-11-30 2023-02-26     1   
5531  42348     Oleg Pozhigan     Dinamo Mn 2022-12-28 2023-03-05     1   
999   42355    Colin Campbell     Kunlun RS 2023-01-03 2023-02-26     1   

           to_team  
3886  Avtomobilist  
3885           NaN  
2000          Ugra  
1999        Vityaz  
1998           NaN  
...            ...  
1019           NaN  
1361           NaN  
2133           NaN  
5531           NaN  
999            NaN  

[8179 rows x 7 columns]

Выберем топ-20 игроков по переходам.

In [ ]:
top_switchers = players.groupby('id').agg(
    num_teams=('team', 'count')).sort_values(by='num_teams', ascending=False)[:20].index

Выделим датафрейм топ-20 игроков по переходам, отсортируем по имени и фамилии игрока и дате прихода в команду.

С пропусками функция работать не будет, поэтому выбираем только строки, где переходы не пустые `to_team == to_team`.

In [ ]:
top_transfers = players.query('id in @top_switchers and to_team == to_team').sort_values(by=['player','start_date'])
top_transfers

id                player            team start_date   end_date  step  \
5861  12990  Alexander Ryazantsev             SKA 2008-09-05 2008-09-13     1   
5860  12990  Alexander Ryazantsev        Avangard 2008-09-30 2009-02-21     2   
5859  12990  Alexander Ryazantsev          Vityaz 2009-09-11 2010-03-07     3   
5858  12990  Alexander Ryazantsev    Avtomobilist 2010-10-03 2011-01-25     4   
5857  12990  Alexander Ryazantsev  Salavat Yulaev 2011-02-01 2011-02-25     5   
...     ...                   ...             ...        ...        ...   ...   
5904  10546           Yakov Rylov    OHC Dynamo M 2016-08-24 2017-03-16     6   
5903  10546           Yakov Rylov     HC Dynamo M 2017-09-21 2018-03-01     7   
5902  10546           Yakov Rylov    Metallurg Mg 2018-09-02 2019-03-07     8   
5901  10546           Yakov Rylov         Spartak 2019-09-02 2021-09-28     9   
5900  10546           Yakov Rylov    Avtomobilist 2021-10-30 2022-01-13    10   

             to_team  
5861        Avangard  
5860          Vityaz  
5859    Avtomobilist  
5858  Salavat Yulaev  
5857         Traktor  
...              ...  
5904     HC Dynamo M  
5903    Metallurg Mg  
5902         Spartak  
5901    Avtomobilist  
5900            Amur  

[209 rows x 7 columns]

In [ ]:
# создаем словарь
source_indexes = get_source_index(top_transfers)
#source_indexes

In [ ]:
# генерим цвета из списка
colors_dict = colors_for_sources(mode='random', df=top_transfers)

In [ ]:
# создаем нужные данные для построения диаграммы
data_for_plot = lists_for_plot(top_transfers, source_indexes, colors_dict)

100%|██████████| 10/10 [00:00<00:00, 128.17it/s]

Шаг: 100%|██████████| 13/13 [00:01<00:00,  6.68it/s]


Все готово для вывода диаграммы!

In [ ]:
# сохраняем диаграмму в переменную и выводим ее
senkey_diagram = plot_senkey_diagram('Переходы топ-20 игроков между командами КХЛ', data_for_plot)
senkey_diagram.show()

Наглядно, красиво, интерактивно)

#### Переходы игроков между топ-5 команд КХЛ.

In [ ]:
top_teams = players.groupby('team').agg(
    num_players=('id', 'count')).sort_values(by='num_players', ascending=False)[:5].index

In [ ]:
top_team_transfers = players.query('team in @top_teams or to_team in @top_teams').sort_values(by=['player','start_date'])
top_team_transfers

id            player         team start_date   end_date  step  \
2261  22255        Adam Huska      Torpedo 2022-09-23 2023-03-22     1   
5429  24854      Adam Polasek     HC Sochi 2017-10-09 2018-03-09     2   
5428  24854      Adam Polasek  Neftekhimik 2018-09-03 2019-02-20     3   
6686  15293       Ahren Spylo       Vityaz 2008-09-02 2008-12-02     1   
5410  15493    Ainars Podzins     Dinamo R 2010-09-09 2012-09-10     1   
...     ...               ...          ...        ...        ...   ...   
2403  22144       Ziga Jeglic  Neftekhimik 2017-10-22 2018-01-23     3   
5411  21331  Zigurds Podzinsh         Amur 2015-08-26 2016-11-27     1   
5046  18686      Ziyat Paigin     HC Sochi 2018-12-10 2019-03-05     5   
5045  18686      Ziyat Paigin  Neftekhimik 2019-09-06 2020-03-08     6   
5044  18686      Ziyat Paigin      Torpedo 2020-09-27 2022-09-12     7   

          to_team  
2261          NaN  
5429  Neftekhimik  
5428          NaN  
6686          NaN  
5410       Vityaz  
...           ...  
2403       Slovan  
5411          NaN  
5046  Neftekhimik  
5045      Torpedo  
5044     Avangard  

[2649 rows x 7 columns]

In [ ]:
top_team_transfers['step'] = top_team_transfers.groupby(['id']).cumcount() + 1
top_team_transfers.sort_values(by='step', ascending=False)

id             player         team start_date   end_date  step  \
8081  13679     Mikhail Zhukov      Torpedo 2017-09-16 2018-03-07    10   
2866   5433      Gleb Klimenko         Amur 2016-08-31 2016-09-27     9   
8082  13679     Mikhail Zhukov  Neftekhimik 2016-12-13 2017-01-19     9   
2634  13710       Ivan Kasutin  Neftekhimik 2016-12-22 2017-02-18     9   
4800   8875  Alexander Nikulin       Vityaz 2015-10-05 2019-02-28     8   
...     ...                ...          ...        ...        ...   ...   
3634  17149      Kevin Lalande       Vityaz 2010-09-10 2011-02-14     1   
5891  35659       Kerby Rychel  Neftekhimik 2019-09-17 2019-09-30     1   
50    40283     Kenny Agostino      Torpedo 2021-09-02 2023-03-02     1   
7697  13728      Alexei Yakhin      Spartak 2009-10-21 2009-10-31     1   
2261  22255         Adam Huska      Torpedo 2022-09-23 2023-03-22     1   

        to_team  
8081        NaN  
2866        NaN  
8082    Torpedo  
2634        NaN  
4800        NaN  
...         ...  
3634  Dinamo Mn  
5891        NaN  
50          NaN  
7697  Severstal  
2261        NaN  

[2649 rows x 7 columns]

In [ ]:
source_indexes = get_source_index(top_team_transfers)
colors_dict = colors_for_sources(mode='random', df=top_team_transfers)
data_for_plot = lists_for_plot(top_team_transfers, source_indexes, colors_dict)

100%|██████████| 7/7 [00:00<00:00, 117.87it/s]

100%|██████████| 4/4 [00:00<00:00, 234.24it/s]

Шаг: 100%|██████████| 10/10 [00:05<00:00,  1.71it/s]


In [ ]:
senkey_diagram = plot_senkey_diagram('Переходы игроков между топ-5 команд КХЛ', data_for_plot, 2000, 2000)
senkey_diagram.show()

И снова красота)

### **Сhord** диаграммы


#### Переходы топ-20 игроков между командами

In [ ]:
top_transfers

id                player            team start_date   end_date  step  \
5861  12990  Alexander Ryazantsev             SKA 2008-09-05 2008-09-13     1   
5860  12990  Alexander Ryazantsev        Avangard 2008-09-30 2009-02-21     2   
5859  12990  Alexander Ryazantsev          Vityaz 2009-09-11 2010-03-07     3   
5858  12990  Alexander Ryazantsev    Avtomobilist 2010-10-03 2011-01-25     4   
5857  12990  Alexander Ryazantsev  Salavat Yulaev 2011-02-01 2011-02-25     5   
...     ...                   ...             ...        ...        ...   ...   
5904  10546           Yakov Rylov    OHC Dynamo M 2016-08-24 2017-03-16     6   
5903  10546           Yakov Rylov     HC Dynamo M 2017-09-21 2018-03-01     7   
5902  10546           Yakov Rylov    Metallurg Mg 2018-09-02 2019-03-07     8   
5901  10546           Yakov Rylov         Spartak 2019-09-02 2021-09-28     9   
5900  10546           Yakov Rylov    Avtomobilist 2021-10-30 2022-01-13    10   

             to_team  
5861        Avangard  
5860          Vityaz  
5859    Avtomobilist  
5858  Salavat Yulaev  
5857         Traktor  
...              ...  
5904     HC Dynamo M  
5903    Metallurg Mg  
5902         Spartak  
5901    Avtomobilist  
5900            Amur  

[209 rows x 7 columns]

In [ ]:
top_transfers['id'] = top_transfers['id'].astype(int)
# Для построения диаграммы нужны id команд, создадим их - выделим команды, пронумеруем их и добавим к датафрейму
tr_list = top_transfers['team'].unique().tolist() + top_transfers['to_team'].unique().tolist()
tr_list_1 = np.arange(0, len(set(tr_list))).tolist()

set(tr_list)

keys = list(set(tr_list))
dic = {k: v for k, v in zip(keys, tr_list_1)}

#Добавляем к датафрейму
top_transfers['id_from'] = top_transfers.team.map(dic)
top_transfers['id_to'] = top_transfers.to_team.map(dic)

#Считаем количество переходов
transfers_count = top_transfers.groupby(['id_from', 'id_to']).start_date.count().reset_index()

#Добавляем названия узлов
tms = pd.DataFrame.from_dict(dic, 'index').reset_index().rename(columns={'index': 'name', 0:'index'})
nodes = hv.Dataset(tms, 'index', 'name')


chord = hv.Chord((transfers_count, nodes), ['id_from', 'id_to'], ['start_date'])

chord.opts(
    opts.Chord(title='Переходы топ-20 игроков между командами', cmap='Category20', edge_cmap='Category20', edge_color=dim('id_from').str(),
               labels='name', node_color=dim('index').str()))

hv.output(size=300)
output_file('test.html')
show(hv.render(chord))

#### Топ-20 по количеству переходов между двумя командами.

In [ ]:
top_team_transfers = players.query('to_team == to_team ')
top_team_transfers

id             player            team start_date   end_date  step  \
3886      1     Evgeny Lobanov         Torpedo 2008-11-12 2009-11-21     1   
2000     11   Denis Grebeshkov             SKA 2010-09-09 2012-10-26     1   
1999     11   Denis Grebeshkov            Ugra 2012-11-02 2013-02-17     2   
3535     18    Andrei Kuteikin  Salavat Yulaev 2008-09-02 2013-03-01     1   
3534     18    Andrei Kuteikin             SKA 2013-09-06 2016-03-26     2   
...     ...                ...             ...        ...        ...   ...   
6868  39993  Alexander Suvorov       Dinamo Mn 2021-09-03 2022-03-08     1   
4257  40152     Johan Mattsson        Dinamo R 2021-09-02 2021-12-12     1   
7641  40257        Anton Wedin           Sibir 2021-09-07 2021-10-14     1   
1987  40685      Tyler Graovac       Dinamo Mn 2021-09-03 2022-03-08     1   
425   41184      Mark Barberio         Ak Bars 2021-12-25 2022-01-11     1   

           to_team  
3886  Avtomobilist  
2000          Ugra  
1999        Vityaz  
3535           SKA  
3534      Avangard  
...            ...  
6868     Severstal  
4257  Avtomobilist  
7641    Dynamo Msk  
1987        Vityaz  
425      Dinamo Mn  

[4459 rows x 7 columns]

In [ ]:
# Для построения диаграммы нужны id команд, создадим их - выделим команды, пронумеруем их и добавим к датафрейму
tr_list = top_team_transfers['team'].unique().tolist() + top_team_transfers['to_team'].unique().tolist()
tr_list_1 = np.arange(0, len(set(tr_list))).tolist()

set(tr_list)

keys = list(set(tr_list))
dic = {k: v for k, v in zip(keys, tr_list_1)}

#Добавляем к датафрейму
top_team_transfers['id_from'] = top_team_transfers.team.map(dic)
top_team_transfers['id_to'] = top_team_transfers.to_team.map(dic)


<ipython-input-284-1c126b90c47c>:11: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-284-1c126b90c47c>:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [ ]:
top_trs = top_team_transfers.groupby(['team','id_from','to_team','id_to'], as_index=False).agg(
    num_players=('id', 'count')).sort_values(by='num_players', ascending=False)[:20]
top_trs

team  id_from         to_team  id_to  num_players
681             SKA       33        HC Sochi      5           28
364     HC Dynamo M       20      Dynamo Msk      4           23
379          HC MVD       29    OHC Dynamo M      7           21
758       Severstal       35         Spartak      2           19
699             SKA       33          Vityaz     24           19
649    OHC Dynamo M        7     HC Dynamo M     20           19
234            CSKA        3  Salavat Yulaev     17           18
216            CSKA        3        Avangard     21           17
616     Neftekhimik       23    Avtomobilist     26           17
763           Sibir       28         Admiral     30           16
637     Neftekhimik       23         Spartak      2           16
110          Atlant       31         Spartak      2           16
695             SKA       33         Spartak      2           16
641     Neftekhimik       23          Vityaz     24           15
168    Avtomobilist       26     Neftekhimik     23           15
955          Vityaz       24             SKA     33           15
724  Salavat Yulaev       17         Spartak      2           15
873         Torpedo       36            Ugra     37           15
144        Avangard       21         Traktor      6           15
138        Avangard       21  Salavat Yulaev     17           15

In [ ]:
#Создаем датасет с узлами - это уникальные id и названия команд
trs_nodes = pd.concat([
    top_trs[['id_from', 'team']].rename(columns={'id_from': 'id'}),
    top_trs[['id_to', 'to_team']].rename(columns={'id_to': 'id', 'to_team': 'team'})
], ignore_index=True, axis=0).drop_duplicates()

In [ ]:
#чтобы график построился, передаем узлы в holoview
nodes = hv.Dataset(trs_nodes, 'id', 'team')

#и строим диаграмму - передаем ребра (связь - откуда - куда) и узлы (названия команд), num_players - как бы "ширина" ребра, сколько переходов было
chord = hv.Chord((top_trs, nodes), ['id_from', 'id_to'], ['num_players'])

chord.opts(
    opts.Chord(title='Топ-20 переходов между командами', cmap='Category20', edge_cmap='Category20', edge_color=dim('id_from'),
               labels='team', tools=['hover'], node_color=dim('id').str()))
hv.extension('bokeh')
hv.output(size=300)
output_file('test.html')
show(hv.render(chord))

Output hidden; open in https://colab.research.google.com to view.

## Поиск одноклубников
Для нахождения одноклубников присоединим таблицу к самой себе по столбцам командой, если игрок является одноклубником самому себе, удалим его из одноклубников.

In [ ]:
peers = players[['id','player','team','start_date','end_date']].merge(players[['id','player','team','start_date','end_date']], on=['team'])

In [ ]:
peers = peers.query('id_x != id_y')

In [ ]:
peers

id_x        player_x     team start_date_x end_date_x   id_y  \
1            1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21     86   
2            1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21     99   
3            1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21    119   
4            1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21    125   
5            1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21    296   
...        ...             ...      ...          ...        ...    ...   
2185583  40293    Tommi Laakso  Jokerit   2021-12-10 2022-01-11  39916   
2185584  40293    Tommi Laakso  Jokerit   2021-12-10 2022-01-11  40258   
2185585  40293    Tommi Laakso  Jokerit   2021-12-10 2022-01-11  40259   
2185586  40293    Tommi Laakso  Jokerit   2021-12-10 2022-01-11  40260   
2185587  40293    Tommi Laakso  Jokerit   2021-12-10 2022-01-11  40261   

                      player_y start_date_y end_date_y  
1              Dmitry Kazionov   2014-09-04 2015-03-05  
2              Evgeny Skachkov   2014-01-17 2014-03-18  
3              Nikolai Zherdev   2015-12-02 2017-02-27  
4                Ilya Krikunov   2008-11-28 2013-01-10  
5        Alexander Yevseyenkov   2010-09-09 2013-09-08  
...                        ...          ...        ...  
2185583          Janne Juvonen   2021-09-02 2021-12-30  
2185584           Samuli Tervo   2021-12-20 2022-01-11  
2185585           Niko Mikkola   2021-12-12 2021-12-12  
2185586      Niclas Tenhovuori   2021-12-20 2021-12-22  
2185587         Kristjan Kombe   2021-12-20 2021-12-26  

[2176272 rows x 9 columns]

Промаркируем тех, кто играл в одном клубе в одно время  с помощью пересечения интервалов - даты игрока пересекаем с датами одноклубника, если есть общие интервалы, функция возвращает - True, иначе - False.

In [ ]:
peers['peer_flag'] = peers.apply(lambda x: pd.Interval(x['start_date_x'], x['end_date_x'], closed='both').overlaps(pd.Interval(x['start_date_y'], x['end_date_y'], closed='both')), axis=1)

In [ ]:
peers.peer_flag.value_counts()

False    1758350
True      417922
Name: peer_flag, dtype: int64

Количество строчек с одноклубниками - 417922

Посмотрим топ-75 игроков по количеству одноклубников за время карьеры и существования КХЛ.

In [ ]:
true_peers = peers[peers['peer_flag'] == True]

In [ ]:
true_peers.head()

id_x        player_x     team start_date_x end_date_x  id_y  \
4      1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21   125   
13     1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21  3450   
21     1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21  3601   
22     1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21  3602   
26     1  Evgeny Lobanov  Torpedo   2008-11-12 2009-11-21  3682   

              player_y start_date_y end_date_y  peer_flag  
4        Ilya Krikunov   2008-11-28 2013-01-10       True  
13  Grigory Shafigulin   2009-09-11 2010-03-05       True  
21    Evgeny Shaldybin   2008-09-03 2010-03-03       True  
22  Timofei Shishkanov   2008-10-30 2009-03-05       True  
26   Mikhail Lyubushin   2008-11-14 2009-12-07       True

In [ ]:
num_peers = true_peers.groupby(['id_x', 'player_x'])['id_y'].nunique().reset_index(
    name='num_peers').sort_values(by = 'num_peers', ascending=False)
num_peers[:75]

id_x           player_x  num_peers
209    4351    Evgeny Lapenkov        475
47      548  Gennady Stolyarov        467
636   14299     Denis Kazionov        464
770   14815   Vladimir Galuzin        454
40      494      Denis Parshin        446
...     ...                ...        ...
532   13705  Nikolai Lemtyugov        357
103    3641       Igor Radulov        357
1038  15508  Anatoly Nikontsev        356
322    5457     Renat Mamashev        355
654   14365   Mikhail Biryukov        353

[75 rows x 3 columns]

Николай Лемтюгов только на 71-ом месте, у него 357 одноклубников. У первой тройки игроков число одноклубников около 470.

## Рассчет числа Лемтюгова. Создание графа.

In [ ]:
real_peers = peers[peers['peer_flag'] == True].copy()
real_peers = real_peers[['id_x', 'id_y']]
real_peers.reset_index(drop=True, inplace=True)
real_peers

id_x   id_y
0           1    125
1           1   3450
2           1   3601
3           1   3602
4           1   3682
...       ...    ...
417917  40293  39916
417918  40293  40258
417919  40293  40259
417920  40293  40260
417921  40293  40261

[417922 rows x 2 columns]

Создадим граф. В качестве графа будет выступать словарь с игроками и их одноклубниками.

In [ ]:
dicto = real_peers.groupby('id_x').agg({'id_y': 'unique'}).to_dict()

In [ ]:
#Убираем индекс - перекладываем значения в новый словарь
newd = {}
for k, v in dicto.items():
    newd.update(v)

In [ ]:
#Конвертируем значения из массива в список
for k, v in newd.items():
    newd[k] = v.tolist()

Напишем функцию для обхода графа и поиска кратчайшего пути между его вершинами.

Будем использовать такой тип данных, как очередь, и сохранять результаты обхода в словарь.

Источники вдохновения:

https://www.pythonforbeginners.com/data-structures/shortest-path-length-from-a-vertex-to-other-vertices-in-a-graph

https://pimiento.github.io/python_graphs.html - если заходим выводить не просто число, а путь до игрока, можно использовать мануалы с этой страницы.

In [ ]:
#@title
def calculate_distance(input_graph, source):
    Q = Queue()
    distance_dict = {k: 999999999 for k in input_graph.keys()}
    visited_vertices = list()
    Q.put(source)
    visited_vertices.append(source)
    while not Q.empty():
        vertex = Q.get()
        if vertex == source:
            distance_dict[vertex] = 0
        for u in input_graph[vertex]:
            if u not in visited_vertices:
                # update the distance
                if distance_dict[u] > distance_dict[vertex] + 1:
                    distance_dict[u] = distance_dict[vertex] + 1
                Q.put(u)
                visited_vertices.append(u)
    return distance_dict

Т.к. у нас id игроков, то нужно получить имя - для этого ранее создавался словарь с соответствиями id игроков и их имен.

### Николай Лемтюгов

In [ ]:
search_name = 'Nikolai Lemtyugov'
[id for id, name in players_dict_2.items() if name == search_name]

[13705]

Рассчитываем число Лемтюгова - чем число больше, тем дальше игроки друг от друга, если число равно 999999999, то игроки не связаны

In [ ]:
distances = calculate_distance(newd, 13705)

In [ ]:
# Преобразуем словарь в датафрейм
lemtyugov_number = pd.DataFrame.from_dict(distances, orient='index').reset_index().rename(columns={'index': 'id', 0: 'number_lem'})

# Добавляем имя игрока из словаря с id игроков
lemtyugov_number['player'] = lemtyugov_number['id'].map(players_dict_2)

#Меняем порядок столбцов и сортируем по числу в порядке убывания
lemtyugov_number = lemtyugov_number[['id', 'player', 'number_lem']]
lemtyugov_number.sort_values(by='number_lem', ascending=False)

id             player  number_lem
3719  42355     Colin Campbell           3
60     3496      Marat Davydov           3
3555  39297      Samuel Jukuri           3
3100  28240      Paris O'Brien           3
3102  28392        Pengfei Han           3
...     ...                ...         ...
1635  17457      Ilya Khokhlov           1
716   14613      Ilya Kablukov           1
1633  17429    Andrei Yermakov           1
526   13683    Roman Kukumberg           1
532   13705  Nikolai Lemtyugov           0

[3720 rows x 3 columns]

In [ ]:
lemtyugov_number['number_lem'].agg(['mean', 'median'])

mean      1.923656
median    2.000000
Name: number_lem, dtype: float64

Получается, если взять всех игроков в КХЛ, то любой из них связан с Лемтюговым максимум через трех других игроков. Игроков без числа Лемтюгова не найдено.

Таким образом можно рассчитать расстояние между двумя любыми игроками в КХЛ.

Проверим еще одного игрока с большим числом переходов и одноклубников - Евгения Лапенкова.

### Евгений Лапенков

In [ ]:
search_name = 'Evgeny Lapenkov'
[id for id, name in players_dict_2.items() if name == search_name]

[4351]

In [ ]:
distances = calculate_distance(newd, 4351)
lapenkov_number = pd.DataFrame.from_dict(distances, orient='index').reset_index().rename(columns={'index': 'id', 0: 'number_lem'})
lapenkov_number['player'] = lapenkov_number['id'].map(players_dict_2)
lapenkov_number = lapenkov_number[['id', 'player', 'number_lem']]
lapenkov_number.sort_values(by='number_lem', ascending=False)

id               player  number_lem
3719  42355       Colin Campbell           3
3584  39693  Alexander Perevalov           3
2087  19544     Maxim S. Baranov           3
2575  22723         Ilya Lobanov           3
2037  19261    Vladislav Nikulin           3
...     ...                  ...         ...
2870  24965       Matej Stransky           1
839   15054   Denis Fakhrutdinov           1
835   15031      Denis Kurepanov           1
0         1       Evgeny Lobanov           1
209    4351      Evgeny Lapenkov           0

[3720 rows x 3 columns]

In [ ]:
lapenkov_number['number_lem'].agg(['mean', 'median'])

mean      1.888978
median    2.000000
Name: number_lem, dtype: float64

И у него медианное число равно 2, хотя среднее немного ниже, чем у Лемтюгова.

Есть ли разница в количестве связей у игроков, которые играли всего в одной команде?

Проверим еще одного игрока, который играл только в одной команде.

In [ ]:
players.groupby(['id', 'player']).agg(
    num_teams=('team', 'nunique')).sort_values(by = 'num_teams', ascending=True)[:5]

num_teams
id    player                   
42355 Colin Campbell          1
24079 Hynek Zohorna           1
24081 Libor Kasik             1
16777 Tomas Bulik             1
16770 Oscar Lindberg          1

### Либор Касик
Узнаем id игрока.

In [ ]:
search_name = 'Libor Kasik'
[id for id, name in players_dict_2.items() if name == search_name]

[24081]

Заодно проверим количество трансферов и одноклубников.

In [ ]:
num_transfers.query('id == 24081')

id       player  num_transfers
2763  24081  Libor Kasik              1

In [ ]:
num_peers.query('id_x == 24081')

id_x     player_x  num_peers
2763  24081  Libor Kasik         35

Всё логично, одна команда, один трансфер, 35 одноклубников.

Посчитаем расстояние.

In [ ]:
distances = calculate_distance(newd, 24081)
kasik_number = pd.DataFrame.from_dict(distances, orient='index').reset_index().rename(columns={'index': 'id', 0: 'number_lem'})
kasik_number['player'] = kasik_number['id'].map(players_dict_2)
kasik_number = kasik_number[['id', 'player', 'number_lem']]
kasik_number.sort_values(by='number_lem', ascending=False)

id               player  number_lem
3073  27444   Kristian Afanasyev           4
3712  42126       Matteo Gennaro           4
3719  42355       Colin Campbell           3
2862  24929          Adam Masuhr           3
1445  16645  Alexander Hellstrom           3
...     ...                  ...         ...
1798  17940    Vladislav Ushenin           1
1210  16001      Bogdan Potekhin           1
618   14263       Igor Velichkin           1
1382  16386     Kirill Rasskazov           1
2763  24081          Libor Kasik           0

[3720 rows x 3 columns]

In [ ]:
kasik_number['number_lem'].agg(['mean', 'median'])

mean      2.477419
median    2.000000
Name: number_lem, dtype: float64

Для игрока, игравшего всего в одной команде, максимальной число игроков, связывающих его с самым дальним игроком, т.е. число Лемтюгова, равно 4. Медиана осталась прежней 2, а среднее увеличелось до 2,5.

## Визуализация графов.

Нам понадобится библиотека для работы с графами: https://networkx.org/documentation/stable/index.html

И еще полезная ссылка про графы: https://habr.com/ru/companies/ruvds/articles/705368/

In [ ]:
real_peers.groupby('id_x').agg({'id_y': 'unique'})

id_y
id_x                                                    
1      [125, 3450, 3601, 3602, 3682, 3754, 3999, 4113...
11     [266, 279, 392, 525, 3541, 3582, 3621, 3649, 4...
18     [99, 524, 3582, 5936, 9467, 10176, 12812, 1325...
41     [139, 516, 595, 3510, 3613, 3614, 3637, 3675, ...
43     [525, 3521, 3593, 3945, 6140, 8875, 13121, 134...
...                                                  ...
42245  [14867, 17845, 17846, 17901, 17904, 17906, 185...
42267  [10546, 13252, 15323, 15646, 16008, 16080, 164...
42322  [13871, 14148, 15247, 15308, 15413, 15481, 160...
42348  [14444, 15586, 16056, 16171, 16230, 19066, 210...
42355  [16740, 24710, 26926, 27224, 27292, 27316, 273...

[3720 rows x 1 columns]

Добавим имена игроков.

In [ ]:
real_peers_names = pd.DataFrame()
real_peers_names['id_x'] = real_peers['id_x']
real_peers_names['player_x'] = real_peers['id_x'].map(players_dict_2)
real_peers_names['id_y'] = real_peers['id_y']
real_peers_names['player_y'] = real_peers['id_y'].map(players_dict_2)
real_peers_names

id_x        player_x   id_y            player_y
0           1  Evgeny Lobanov    125       Ilya Krikunov
1           1  Evgeny Lobanov   3450  Grigory Shafigulin
2           1  Evgeny Lobanov   3601    Evgeny Shaldybin
3           1  Evgeny Lobanov   3602  Timofei Shishkanov
4           1  Evgeny Lobanov   3682   Mikhail Lyubushin
...       ...             ...    ...                 ...
417917  40293    Tommi Laakso  39916       Janne Juvonen
417918  40293    Tommi Laakso  40258        Samuli Tervo
417919  40293    Tommi Laakso  40259        Niko Mikkola
417920  40293    Tommi Laakso  40260   Niclas Tenhovuori
417921  40293    Tommi Laakso  40261      Kristjan Kombe

[417922 rows x 4 columns]

### Топ-75, библиотека Networkx

Выделим топ-75 игроков по количеству одноклубников.

In [ ]:
top_id = peers[peers['peer_flag']==True].groupby(['id_x'])['id_y'].nunique().sort_values(ascending=False)[:75].index.to_list()
top_ids = real_peers_names.query('id_x in @top_id')

In [ ]:
top_ids

id_x         player_x   id_y             player_y
121       119  Nikolai Zherdev    372      Oleg Piganovich
122       119  Nikolai Zherdev   3564      Vadim Khomitsky
123       119  Nikolai Zherdev   3593         Dmitry Semin
124       119  Nikolai Zherdev   3694  Alexander A. Frolov
125       119  Nikolai Zherdev   4486     Maxim Kondratyev
...       ...              ...    ...                  ...
412083  15373      Geoff Platt  27752        Eeli Tolvanen
412084  15373      Geoff Platt  30734      Sakari Manninen
412085  15373      Geoff Platt  31190       Eemeli Rasanen
412086  15373      Geoff Platt  31415          Viktor Loov
412087  15373      Geoff Platt  31481           Alex Grant

[32968 rows x 4 columns]

In [ ]:
#Создаем граф из таблицы pandas на примере метода from_pandas_edgelist библиотеки Networks
G = nx.from_pandas_edgelist(top_ids, 'player_x', 'player_y')
pos = nx.spring_layout(G)

In [ ]:
#Добавляем атрибут с информацией по расположению узлов (можно задать через set_attribute)
for node in G.nodes:
    G.nodes[node]['pos'] = list(pos[node])

In [ ]:
list(G.nodes(data=True))[0:5]

[('Nikolai Zherdev', {'pos': [0.1397974193096161, -0.144403338432312]}),
 ('Oleg Piganovich', {'pos': [0.04390113800764084, -0.1451258808374405]}),
 ('Vadim Khomitsky', {'pos': [0.07996606081724167, -0.011082426644861698]}),
 ('Dmitry Semin', {'pos': [0.06033500283956528, 0.049203913658857346]}),
 ('Alexander A. Frolov', {'pos': [0.13618865609169006, 0.055544376373291016]})]

Вот так выглядят первые 5 узлов (nodes) в нашем графе.

Возьмем код с Plotly: https://plotly.com/python/network-graphs/ для отрисовки графа.

In [ ]:
edge_x = []
edge_y = []
for edge in G.edges():
    x0, y0 = G.nodes[edge[0]]['pos']
    x1, y1 = G.nodes[edge[1]]['pos']
    edge_x.append(x0)
    edge_x.append(x1)
    edge_x.append(None)
    edge_y.append(y0)
    edge_y.append(y1)
    edge_y.append(None)

edge_trace = go.Scatter(
    x=edge_x, y=edge_y,
    line=dict(width=0.5, color='#888'),
    hoverinfo='none',
    mode='lines')

node_x = []
node_y = []
for node in G.nodes():
    x, y = G.nodes[node]['pos']
    node_x.append(x)
    node_y.append(y)

node_trace = go.Scatter(
    x=node_x, y=node_y,
    mode='markers',
    hoverinfo='text',
    marker=dict(
        showscale=True,
        # colorscale options
        #'Greys' | 'YlGnBu' | 'Greens' | 'YlOrRd' | 'Bluered' | 'RdBu' |
        #'Reds' | 'Blues' | 'Picnic' | 'Rainbow' | 'Portland' | 'Jet' |
        #'Hot' | 'Blackbody' | 'Earth' | 'Electric' | 'Viridis' |
        colorscale='Hot',
        reversescale=True,
        color=[],
        size=10,
        colorbar=dict(
            thickness=15,
            title='Node Connections',
            xanchor='left',
            titleside='right'
        ),
        line_width=2))

In [ ]:
node_adjacencies = []
node_text = []
for node, adjacencies in enumerate(G.adjacency()):
    node_adjacencies.append(len(adjacencies[1]))
    node_text.append('player: '+str(adjacencies[0])+ ' ' + '# of connections: '+str(len(adjacencies[1])))

node_trace.marker.color = node_adjacencies
node_trace.text = node_text

In [ ]:
fig = go.Figure(data=[edge_trace, node_trace],
             layout=go.Layout(width=1200, height=1200,
                title='Граф топ-75 игроков и их связей',
                titlefont_size=16,
                showlegend=False,
                hovermode='closest',
                margin=dict(b=20,l=5,r=5,t=40),
                annotations=[ dict(
                    text="",
                    showarrow=False,
                    xref="paper", yref="paper",
                    x=0.005, y=-0.002 ) ],
                xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                yaxis=dict(showgrid=False, zeroline=False, showticklabels=False))
                )
fig.show()

Output hidden; open in https://colab.research.google.com to view.

Топ-75 был обусловлен тем, что Николай Лемтюгов только на 71 первом месте, хотелось, чтобы его можно было найти на графике и он тут есть. =)

### Топ-10, библиотека Holoview

Визуализация графов с помощью Holoview:

https://holoviews.org/user_guide/Network_Graphs.html

Выделим топ-10 игроков и их граф.

In [ ]:
top_id_10 = peers[peers['peer_flag']==True].groupby(['id_x'])['id_y'].nunique().sort_values(ascending=False)[:10].index.to_list()
top_ids_10 = real_peers_names.query('id_x in @top_id_10')

In [ ]:
G_10 = nx.from_pandas_edgelist(top_ids_10, 'player_x', 'player_y')
pos_10 = nx.spring_layout(G_10)

In [ ]:
kwargs = dict(width=800, height=800, xaxis=None, yaxis=None)
opts.defaults(opts.Nodes(**kwargs), opts.Graph(**kwargs))

colors = ['#000000']+hv.Cycle('Category20').values

graph = hv.Graph.from_networkx(G_10, pos_10)

graph.opts(cmap=colors, node_size=5, edge_line_width=1,
              node_line_color='gray')

hv.extension('bokeh')
hv.output(size=100)
output_file('test.html')
show(hv.render(graph))

Output hidden; open in https://colab.research.google.com to view.

График интерактивный, на нем хорошо видны все одноклубники топов и ребра между ними.

### Топ-5, библиотека Holoview

Визуализация графов с помощью Holoview:

https://holoviews.org/user_guide/Network_Graphs.html

Выделим топ-5 игроков и их граф.

In [ ]:
top_id_5 = peers[peers['peer_flag']==True].groupby(['id_x'])['id_y'].nunique().sort_values(ascending=False)[:5].index.to_list()
top_ids_5 = real_peers_names.query('id_x in @top_id_5')

In [ ]:
G_5 = nx.from_pandas_edgelist(top_ids_5, 'player_x', 'player_y')

pos_5 = nx.spring_layout(G_5)

In [ ]:
# !pip install scikit-image --quiet
# !pip install datashader --quiet

In [ ]:
kwargs = dict(width=800, height=800, xaxis=None, yaxis=None)
opts.defaults(opts.Nodes(**kwargs), opts.Graph(**kwargs))

colors = ['#000000']+hv.Cycle('Category20').values

graph = hv.Graph.from_networkx(G_5, pos_5)

graph.opts(cmap=colors, node_size=5, edge_line_width=1,
              node_line_color='gray')

bundled = bundle_graph(graph)

hv.extension('bokeh')
hv.output(size=100)
output_file('test.html')
show(hv.render(bundled))

Output hidden; open in https://colab.research.google.com to view.

График интерактивный, на нем хорошо видны все одноклубники топов и как они между собой связаны.

## Проверка гипотез

### гипотеза 1:
Проверить гипотезу о том, что Лемтюгов – самый популярный хоккеист в лиге, то есть обладающий самым большим количеством одноклубников. Если это не так, составить список наиболее популярных игроков.

Ход нашего исследования показал, что у Николая Лемтюгова было 357 одноклубников, это только 71 место по данному показателю.
Топ - 10 выглядит так.

In [ ]:
peers[peers['peer_flag'] == True].groupby(['id_x', 'player_x'])['id_y'].nunique().sort_values(ascending=False)[:10]

id_x   player_x          
4351   Evgeny Lapenkov       475
548    Gennady Stolyarov     467
14299  Denis Kazionov        464
14815  Vladimir Galuzin      454
494    Denis Parshin         446
14674  Alexander Lazushin    445
10546  Yakov Rylov           443
14867  Mikhail Grigoryev     437
13871  Ilya Proskuryakov     436
15846  Nikita Tochitsky      430
Name: id_y, dtype: int64

**Гипотеза не подтверждена.**

### гипотеза 2
Правда ли, что игроки с низким значением числа Лемтюгова играли в среднем в большем количестве команд, чем игроки, у которых это значение больше?

* Объединим ранее полученные таблицы:    
    * одноклубников
    * с расчетом расстояния от Лемтюгова до каждого игрока

In [ ]:
real_peers.head()

id_x  id_y
0     1   125
1     1  3450
2     1  3601
3     1  3602
4     1  3682

In [ ]:
lemtyugov_number.head()

id            player  number_lem
0   1    Evgeny Lobanov           2
1  11  Denis Grebeshkov           2
2  18   Andrei Kuteikin           1
3  41       Denis Bayev           1
4  43    Sergei Gimayev           2

In [ ]:
real_peers_with_num = real_peers.merge(lemtyugov_number[['id', 'number_lem']], how='left', left_on=['id_x'], right_on= ['id'])

In [ ]:
real_peers_with_num

id_x   id_y     id  number_lem
0           1    125      1           2
1           1   3450      1           2
2           1   3601      1           2
3           1   3602      1           2
4           1   3682      1           2
...       ...    ...    ...         ...
417917  40293  39916  40293           2
417918  40293  40258  40293           2
417919  40293  40259  40293           2
417920  40293  40260  40293           2
417921  40293  40261  40293           2

[417922 rows x 4 columns]

Вычислим среднее и медиану по количеству одноклубников для игроков с числами Лемтюгова равными 1, 2 и 3.

In [ ]:
real_peers_with_num.query('number_lem == 1').groupby(['id_x']).agg(
    num_peers= ('id_y', 'nunique')).agg(
    ['mean', 'median'])

num_peers
mean    213.731092
median  214.000000

In [ ]:
real_peers_with_num.query('number_lem == 2').groupby(['id_x']).agg(
    num_peers= ('id_y', 'nunique')).agg(
    ['mean', 'median'])

num_peers
mean     95.69638
median   66.00000

In [ ]:
real_peers_with_num.query('number_lem == 3').groupby(['id_x']).agg(
    num_peers= ('id_y', 'nunique')).agg(
    ['mean', 'median'])

num_peers
mean    37.453333
median  36.000000

Из сравнения средних и медиан по количеству одноклубников видно, что игроки с низким значением числа Лемтюгова играли в среднем в большем количестве команд, чем игроки, у которых это значение выше.

**Гипотеза подтверждена.**

### гипотеза 3
Есть ли игроки, у которых отсутствует число Лемтюгова (нет связей через других
игроков)?

In [ ]:
lemtyugov_number.sort_values(by='number_lem', ascending=False)

id             player  number_lem
3719  42355     Colin Campbell           3
60     3496      Marat Davydov           3
3555  39297      Samuel Jukuri           3
3100  28240      Paris O'Brien           3
3102  28392        Pengfei Han           3
...     ...                ...         ...
1635  17457      Ilya Khokhlov           1
716   14613      Ilya Kablukov           1
1633  17429    Andrei Yermakov           1
526   13683    Roman Kukumberg           1
532   13705  Nikolai Lemtyugov           0

[3720 rows x 3 columns]

Ранее в ходе нашего исследования для всех игроков КХЛ (3720 человек) было найдено число Лемтюгова, что говорит нам о том, что **нет** игроков, у которых отсутствует число Лемтюгова (нет связей через других игроков).

**Гипотеза не подтверждена.**

### гипотеза 4
Каково медианное значение числа Лемтюгова?

* В ходе исследования расстояния между игроками (числа Лемтюгова) были найдены для:
    * Николая Лемтюгова: максимально расстояние 3, 357 одноклубников ,11 трансферов и 10 команд
    * Евгения Лапенкова: максимально расстояние 3, 475 одноклубников, 14 переходов и 9 команд
    * Либора Касика: максимально расстояние 4, 35 одноклубников, 1 трансфер, 1 команда

**Для всех игроков медианное значение числа Лемтюгова ровняется 2.**

### гипотеза 5
Проверить, есть ли связь между количеством переходов и ростом/весом игрока (предполагаем, что игроки, у которых рост выше, лучше играют в хоккей и соответственно чаще переходят из клуба в клуб).

In [ ]:
num_transfers.head()

id             player  num_transfers
524  13679     Mikhail Zhukov             14
209   4351    Evgeny Lapenkov             14
636  14299     Denis Kazionov             13
319   5433      Gleb Klimenko             13
47     548  Gennady Stolyarov             12

In [ ]:
stat_full = num_transfers[['id', 'num_transfers']].merge(stat, how='inner', left_on=['id'],right_on=['id'])

In [ ]:
stat_full.head()

id  num_transfers             player position  month_born       born  \
0  13679             14     Mikhail Zhukov  forward           1 1985-01-03   
1   4351             14    Evgeny Lapenkov  forward           8 1984-08-01   
2  14299             13     Denis Kazionov  forward          12 1987-12-08   
3   5433             13      Gleb Klimenko  forward           7 1983-07-28   
4    548             12  Gennady Stolyarov  forward           8 1986-08-20   

  age country  hight  weight  ...   FOA  TkA   W   L  SOP  GA  Sv  %Sv  GAA  \
0  38  Russia    190      94  ...  27.0  0.0 NaN NaN  NaN NaN NaN  NaN  NaN   
1  38  Russia    192     100  ...  44.0  0.0 NaN NaN  NaN NaN NaN  NaN  NaN   
2  35  Russia    189      96  ...  63.0  0.0 NaN NaN  NaN NaN NaN  NaN  NaN   
3  39  Russia    175      81  ...  22.0  0.0 NaN NaN  NaN NaN NaN  NaN  NaN   
4  36  Russia    193      91  ...  66.0  0.0 NaN NaN  NaN NaN NaN  NaN  NaN   

   SO  
0 NaN  
1 NaN  
2 NaN  
3 NaN  
4 NaN  

[5 rows x 51 columns]

In [ ]:
avg_hight = round(stat_full.hight.mean())
avg_hight

184

In [ ]:
avg_weight = round(stat_full.weight.mean())
avg_weight

87

In [ ]:
high = stat_full.query('hight >= @avg_hight and weight>= @avg_weight')

In [ ]:
round(high.num_transfers.mean(), 3)

2.524

In [ ]:
low = stat_full.query('hight < @avg_hight and weight< @avg_weight')

In [ ]:
round(low.num_transfers.mean(), 3)

1.876

In [ ]:
high_hight = stat_full.query('hight >= @avg_hight')

In [ ]:
round(high_hight.num_transfers.mean(), 3)

2.285

In [ ]:
low_hight = stat_full.query('hight < @avg_hight')

In [ ]:
round(low_hight.num_transfers.mean(), 3)

2.11

In [ ]:
high_weight = stat_full.query('weight>= @avg_weight')

In [ ]:
round(high_weight.num_transfers.mean(), 3)

2.558

In [ ]:
low_weight = stat_full.query('weight< @avg_weight')

In [ ]:
round(low_weight.num_transfers.mean(), 3)

1.816

In [ ]:
corr_matrix = stat_full[['num_transfers', 'hight', 'weight']].corr()
corr_matrix

num_transfers     hight    weight
num_transfers       1.000000  0.028921  0.224565
hight               0.028921  1.000000  0.608682
weight              0.224565  0.608682  1.000000

Рассмотрев разные комбинации (рост и вес выше/ниже среднего, рост выше/ниже среднего, вес выше/ниже среднего) нельзя утверждать, что рост или вес сильно влияют на количество трансферов у игроков, однако замечена слабая корреляция между весом и количеством трансферов. Из наблюдений по весу ниже/выше среднего, можно заметить, что при весе выше среднего количество трансферов выше, возможно игроки, набравшие лишний вес менее привлекательны для команд, что способствует их переходу в другие команды.

**Гипотеза не подтверждена.**

### гипотеза 6
Проверить, верна ли гипотеза о том, что более успешные хоккеисты рождаются в
январе-марте.

Для различных аплуа игроков показатели успешности разные, посмотрим какие амплуа  представлены в данных.

In [ ]:
stat_full.position.unique()

array(['forward', 'defense', 'goaltender'], dtype=object)

Для вратарей показатели успешности будем считать процент отраженных шайб, для защитников и нападающих - количество очков по системе гол + пас и показатель "+/-".

Рассчитаем средние значения для нападающих.

In [ ]:
forward_PTS = round(stat_full.query('position == "forward"')['PTS'].mean())
forward_ps = round(stat_full.query('position == "forward"')['+/-'].mean())
print(forward_PTS, forward_ps)

56 -1


Рассчитаем средние значения для защитников.

In [ ]:
defense_PTS = round(stat_full.query('position == "defense"')['PTS'].mean())
defense_ps = round(stat_full.query('position == "defense"')['+/-'].mean())
print(defense_PTS, defense_ps)

33 0


Рассчитаем средние значения для вратарей.

In [ ]:
goaltender_Sv = round(stat_full.query('position == "goaltender"')['Sv'].mean())
goaltender_Sv

1315

Выделим датафреймы для нападающих, защитников и вратарей

In [ ]:
forwards = stat_full.query('position == "forward"')
defenses = stat_full.query('position == "defense"')
goaltenders = stat_full.query('position == "goaltender"')

#### вратари
Проверим есть ли связь даты рождения и успешности вратарей.

In [ ]:
best_goaltenders = goaltenders.query('Sv >= @goaltender_Sv')
best_goaltenders.head()

id  num_transfers              player    position  month_born  \
7   17553             12        Ivan Nalimov  goaltender           3   
16  13871             10   Ilya Proskuryakov  goaltender           2   
24  14674             10  Alexander Lazushin  goaltender           4   
26  13710             10        Ivan Kasutin  goaltender          10   
30  14365              9    Mikhail Biryukov  goaltender          10   

         born age country  hight  weight  ... FOA  TkA      W      L   SOP  \
7  1994-03-12  29  Russia    195      95  ... NaN  NaN   61.0   86.0  14.0   
16 1987-02-21  36  Russia    182      81  ... NaN  NaN  158.0  133.0  66.0   
24 1988-04-09  35  Russia    182      99  ... NaN  NaN  112.0  133.0  37.0   
26 1986-10-17  36  Russia    182      92  ... NaN  NaN  112.0  135.0  35.0   
30 1985-10-13  37  Russia    183      90  ... NaN  NaN   98.0  128.0  42.0   

       GA      Sv   %Sv   GAA    SO  
7   453.0  4414.0  90,7  2,73  14.0  
16  794.0  8545.0  91,5  2,31  34.0  
24  657.0  7301.0  91,7  2,45  27.0  
26  732.0  7529.0  91,1  2,57  21.0  
30  726.0  7622.0  91,3  2,61  19.0  

[5 rows x 51 columns]

In [ ]:
corr_matrix = best_goaltenders[['month_born', 'Sv']].corr()
corr_matrix

month_born        Sv
month_born    1.000000 -0.019956
Sv           -0.019956  1.000000

Выделим датафреймы вратарей, рожденных с января по март и с апреля по декабрь.

In [ ]:
jan_mar_goaltenders = best_goaltenders.query('1 <= month_born <= 3')['Sv']
apr_dec_goaltenders = best_goaltenders.query('4 <= month_born <= 12')['Sv']

**Нулевая гипотеза H0** - успешность вратарей, рожденных с января по март и с апреля по декабрь равны.

**Альтернативная гипотеза H1** - успешность вратарей, рожденных с января по март и с апреля по декабрь отличаются.

α=0.5% - уровень значимости

Выборки с января по март и с апреля по декабрь не связаны друг с другом. Для расчёта статистики разности и p-value будем использовать функцию st.ttest_ind

In [ ]:
alpha = .05

results = ttest_ind(jan_mar_goaltenders, apr_dec_goaltenders, equal_var=False) # проверка гипотезы о равенстве средних двух независимых совокупностей

print('p-значение:', results.pvalue)

if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

p-значение: 0.38376069209986086
Не получилось отвергнуть нулевую гипотезу


p-value равен 0.38 и больше alpha, в связи с чем нет оснований отвергать нулевую гипотезу. Полученные данные не противоречат гипотезе H0: "успешность вратарей, рожденных с января по март и с апреля по декабрь равны."

**На примере вратарей, гипотеза о том, что более успешные хоккеисты рождаются в
январе-марте, не подтверждена.**

#### нападающие
Проверим есть ли связь даты рождения и успешности для нападающих.

In [ ]:
best_forwards = forwards.query('PTS >= @forward_PTS and `+/-` >= @forward_ps')
best_forwards.head()

id  num_transfers              player position  month_born       born  \
14  16355             11    Alexei Kruchinin  forward           6 1991-06-09   
22  15050             10      Nikita Filatov  forward           5 1990-05-25   
25    125             10       Ilya Krikunov  forward           2 1984-02-27   
32   4707              9  Alexander Korolyuk  forward           1 1976-01-15   
35  14257              9    Yegor Milovzorov  forward          11 1987-11-19   

   age country  hight  weight  ...    FOA   TkA   W   L  SOP  GA  Sv  %Sv  \
14  32  Russia    180      79  ...  134.0  36.0 NaN NaN  NaN NaN NaN  NaN   
22  33  Russia    184      87  ...   40.0   0.0 NaN NaN  NaN NaN NaN  NaN   
25  39  Russia    180      81  ...  128.0   0.0 NaN NaN  NaN NaN NaN  NaN   
32  47  Russia    175      85  ...    9.0   0.0 NaN NaN  NaN NaN NaN  NaN   
35  35  Russia    177      78  ...   81.0   0.0 NaN NaN  NaN NaN NaN  NaN   

    GAA  SO  
14  NaN NaN  
22  NaN NaN  
25  NaN NaN  
32  NaN NaN  
35  NaN NaN  

[5 rows x 51 columns]

In [ ]:
corr_matrix = best_forwards[['month_born', 'PTS', '+/-']].corr()
corr_matrix

month_born       PTS       +/-
month_born    1.000000 -0.047313 -0.031368
PTS          -0.047313  1.000000  0.717975
+/-          -0.031368  0.717975  1.000000

##### гол + пас
Выделим датафреймы нападающих по системе гол + пас, рожденных с января по март и с апреля по декабрь.

In [ ]:
jan_mar_forwards = best_forwards.query('1 <= month_born <= 3')['PTS']
apr_dec_forwards = best_forwards.query('4 <= month_born <= 12')['PTS']

**Нулевая гипотеза H0** - успешность нападающих, рожденных с января по март и с апреля по декабрь равны.

**Альтернативная гипотеза H1** - успешность нападающих, рожденных с января по март и с апреля по декабрь отличаются.

α=0.5% - уровень значимости

Выборки с января по март и с апреля по декабрь не связаны друг с другом. Для расчёта статистики разности и p-value будем использовать функцию st.ttest_ind

In [ ]:
alpha = .05

results = ttest_ind(jan_mar_forwards, apr_dec_forwards, equal_var=False) # проверка гипотезы о равенстве средних двух независимых совокупностей

print('p-значение:', results.pvalue)

if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

p-значение: 0.5215317782629647
Не получилось отвергнуть нулевую гипотезу


p-value равен 0.52 и больше alpha, в связи с чем нет оснований отвергать нулевую гипотезу. Полученные данные не противоречат гипотезе H0: "успешность нападающих рожденных с января по март и с апреля по декабрь равны."

**На примере нападающих (по системе гол + пас), гипотеза о том, что более успешные хоккеисты рождаются в январе-марте, не подтверждена.**

##### показатель +/-
Выделим датафреймы нападающих по показателю +/-, рожденных с января по март и с апреля по декабрь.

In [ ]:
jan_mar_forwards = best_forwards.query('1 <= month_born <= 3')['+/-']
apr_dec_forwards = best_forwards.query('4 <= month_born <= 12')['+/-']

**Нулевая гипотеза H0** - успешность нападающих, рожденных с января по март и с апреля по декабрь равны.

**Альтернативная гипотеза H1** - успешность нападающих, рожденных с января по март и с апреля по декабрь отличаются.

α=0.5% - уровень значимости

Выборки с января по март и с апреля по декабрь не связаны друг с другом. Для расчёта статистики разности и p-value будем использовать функцию st.ttest_ind

In [ ]:
alpha = .05

results = ttest_ind(jan_mar_forwards, apr_dec_forwards, equal_var=False) # проверка гипотезы о равенстве средних двух независимых совокупностей

print('p-значение:', results.pvalue)

if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

p-значение: 0.8704206381073925
Не получилось отвергнуть нулевую гипотезу


p-value равен 0.87 и значительно больше alpha, в связи с чем нет оснований отвергать нулевую гипотезу. Полученные данные не противоречат гипотезе H0: "успешность нападающих рожденных с января по март и с апреля по декабрь равны."

**На примере нападающих (по показателю +/-), гипотеза о том, что более успешные хоккеисты рождаются в январе-марте, не подтверждена.**

#### защитники
Проверим есть ли связь даты рождения и успешности для защитников.

In [ ]:
best_defenses = defenses.query('PTS >= @defense_PTS and `+/-` >= @defense_ps')
best_defenses.head()

id  num_transfers                player position  month_born  \
9   10546             11           Yakov Rylov  defense           1   
11  12990             11  Alexander Ryazantsev  defense           3   
13  14867             11     Mikhail Grigoryev  defense           2   
40  17429              9       Andrei Yermakov  defense           3   
41    516              9         Kirill Lyamin  defense           1   

         born age country  hight  weight  ...   FOA  TkA   W   L  SOP  GA  Sv  \
9  1985-01-15  38  Russia    179      87  ...  68.0  1.0 NaN NaN  NaN NaN NaN   
11 1980-03-15  43  Russia    183     101  ...   2.0  0.0 NaN NaN  NaN NaN NaN   
13 1991-02-01  32  Russia    177      81  ...  47.0  4.0 NaN NaN  NaN NaN NaN   
40 1994-03-12  29  Russia    189     102  ...  17.0  0.0 NaN NaN  NaN NaN NaN   
41 1986-01-13  37  Russia    187      94  ...  18.0  0.0 NaN NaN  NaN NaN NaN   

    %Sv  GAA  SO  
9   NaN  NaN NaN  
11  NaN  NaN NaN  
13  NaN  NaN NaN  
40  NaN  NaN NaN  
41  NaN  NaN NaN  

[5 rows x 51 columns]

In [ ]:
corr_matrix = best_defenses[['month_born', 'PTS', '+/-']].corr()
corr_matrix

month_born       PTS       +/-
month_born    1.000000 -0.047646  0.034184
PTS          -0.047646  1.000000  0.520206
+/-           0.034184  0.520206  1.000000

##### гол + пас
Выделим датафреймы защитников по системе гол + пас, рожденных с января по март и с апреля по декабрь.

In [ ]:
jan_mar_defenses = best_defenses.query('1 <= month_born <= 3')['PTS']
apr_dec_defenses = best_defenses.query('4 <= month_born <= 12')['PTS']

**Нулевая гипотеза H0** - успешность защитников, рожденных с января по март и с апреля по декабрь равны.

**Альтернативная гипотеза H1** - успешность защитников, рожденных с января по март и с апреля по декабрь отличаются.

α=0.5% - уровень значимости

Выборки с января по март и с апреля по декабрь не связаны друг с другом. Для расчёта статистики разности и p-value будем использовать функцию st.ttest_ind

In [ ]:
alpha = .05

results = ttest_ind(jan_mar_defenses, apr_dec_defenses, equal_var=False) # проверка гипотезы о равенстве средних двух независимых совокупностей

print('p-значение:', results.pvalue)

if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

p-значение: 0.31370896634868756
Не получилось отвергнуть нулевую гипотезу


p-value равен 0.31 и больше alpha, в связи с чем нет оснований отвергать нулевую гипотезу. Полученные данные не противоречат гипотезе H0: "успешность защитников рожденных с января по март и с апреля по декабрь равны."

**На примере защитников (по системе гол + пас), гипотеза о том, что более успешные хоккеисты рождаются в январе-марте, не подтверждена.**

##### показатель +/-
Выделим датафреймы защитников по показателю +/-, рожденных с января по март и с апреля по декабрь.

In [ ]:
jan_mar_defenses = best_defenses.query('1 <= month_born <= 3')['+/-']
apr_dec_defenses = best_defenses.query('4 <= month_born <= 12')['+/-']

**Нулевая гипотеза H0** - успешность защитников, рожденных с января по март и с апреля по декабрь равны.

**Альтернативная гипотеза H1** - успешность защитников, рожденных с января по март и с апреля по декабрь отличаются.

α=0.5% - уровень значимости

Выборки с января по март и с апреля по декабрь не связаны друг с другом. Для расчёта статистики разности и p-value будем использовать функцию st.ttest_ind

In [ ]:
alpha = .05

results = ttest_ind(jan_mar_defenses, apr_dec_defenses, equal_var=False) # проверка гипотезы о равенстве средних двух независимых совокупностей

print('p-значение:', results.pvalue)

if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

p-значение: 0.397683687940778
Не получилось отвергнуть нулевую гипотезу


p-value равен 0.4 и значительно больше alpha, в связи с чем нет оснований отвергать нулевую гипотезу. Полученные данные не противоречат гипотезе H0: "успешность защитников рожденных с января по март и с апреля по декабрь равны."

**На примере защитников (по показателю +/-), гипотеза о том, что более успешные хоккеисты рождаются в январе-марте, не подтверждена.**

**На примере всех когорт хоккеистов, гипотеза о том, что более успешные хоккеисты рождаются в январе-марте, не подтверждена.**

## Общий вывод.
**Часть 1:**
* **Загрузка данных.**
    * Загружены 4 датасета с сайта **eliteprospects.com**: информация об игроках КХЛ, информация о переходах, статистика игроков и личные данные игроков.
    * Изучена информация о них.
    * Проверено наличие дубликатов.
* **Предобработка данных.**
    * **Информация об игроках КХЛ.**        
        * Добавлены колонки с датами начала и конца сезона.
        * Удалены лишние колонки.
        * Выделены id игроков и добавлены в новую колонку.
        * Создан словарь, где id - это ключ игрока, а имя и фамилия - это значение словаря.
        * Выделено количество игроков КХЛ.
        * Создан список команд КХЛ, всего 40 команд.
    * **Информация о переходах.**
        * Удалены 7 дубликатов.
        * Выделены id игроков и добавлены в новую колонку.
        * Даты трансферов преобразованы в формат datetime.
        * Созданы функции по определению сезона по дате трансфера для двух случаев, когда игрок покидает команду и когда игрок приходит в команду. Добавлены две соответствующие колонки.
        * Удалены лишние колонки.
        * Датафрейм отфильтрован по id игроков и переходам игроков из или в команды КХЛ. Сброшены индексы.
* **Объединение датафреймов:**
    * с информацией об игроках и переходах:
        * для исходящих трансферов.
        * для входящих трансферов.
    * исходящих и входящих трансферов.
* **Обработка общего датафрейма.**
    * Заменены пропуски в колонке даты перехода игрока в команду, датой начала сезона.
    * Заменены пропуски в колонке даты ухода игрока из команды, датой окончания сезона.
    * Выполнена проверка количество игроков КХЛ в исходном датафрейме и объединенном – все игроки на месте, никого не потеряли.
    * Удалены 2 дубликата.
* **Выводы по исследованию общего датафрема:**
    * Большего всего строчек относится к командам (топ-5): Нефтехимик - 614, ЦСКА - 608, Северсталь - 602, СКА - 597, Амур – 590
    * Количество id игроков - 3599, количество уникальных имен и фамилий игроков - 3561, что свидетельствует о тезках и однофамильцах.
    * В колонке 'To_team' 66% пропусков, это означает, что в конкретном сезоне игрок не переходил в другие команды.

**Часть 2**

* **Загрузка данных.**
    * Загружены 2 датасета с сайта **en.khl.ru** с информацией о периодах нахождения игроков в командах КХЛ и со статистикой игроков.
    * Изучена информация о них.
    * Проверено наличие дубликатов.
* **Предобработка данных.**
    * **Информация о периодах нахождения игроков в командах КХЛ.**
        * Выделены id игроков.
        * Создан словарь, где id - это ключ игрока, а имя и фамилия - это значение словаря.
        * Изучены данные на примере Николая Лемтюгова, периоды прибывания его в разных командах соответствуют действительности.
        * Исследован датафрейм, сформулированы **предварительные выводы:**
            * Большего всего строчек относится к командам (топ-5): Спартак - 370, Нефтехимик - 369, Амур - 356, Торпедо - 352, Витязь -346
            * Количество уникальных id игроков - 3720, количество уникальных имен и фамилий игроков - 3712, что свидетельствует о тезках и однофамильцах.
    * **Статистика игроков КХЛ.**
        * Даты рождения преобразованы в формат datetime.
        * Добавлена колонка с месяцем рождения игрока.
        * Выделены id игроков.        
* **Выделены топы.**
    * Топ-15 игроков по количеству команд за карьеру в КХЛ.
    * Топ-15 игроков по количеству переходов за карьеру в КХЛ.
    * Топ-15 команд по количеству игроков.
* **Визуализация переходов игроков между командами.**
    * **Sankey Chart** диаграммы:
        * Переходы топ-20 игроков между командами КХЛ.
        * Переходы игроков между топ-5 команд КХЛ.
    * **Сhord** диаграммы:
        * Переходы топ-20 игроков между командами.
        * Топ-20 по количеству переходов между двумя командами.
* **Поиск одноклубников.**
    * Создана таблица с одноклубниками, в которой образованы пары игроков, которые когда-либо находились в одном клубе.
    * Промаркированы пары игроков, которые играли в одном клубе в одно время.
    * Сформирован топ-75 игроков по количеству одноклубников за время существования КХЛ. Николай Лемтюгов на 71 месте и у него 357 одноклубников. У первой тройки игроков число одноклубников около 470.
* **Расчет числа Лемтюгова.**
    * Создан граф – словарь с игроками и их одноклубниками.
    * Создана функция обхода графа и поиска кратчайшего пути между его вершинами.
    * Рассчитаны расстояния (количество рукопожатий) или Число Лемтюгова:
        * от **Николая Лемтюгова** до всех игроков КХЛ. Максимальное расстояние 3, медианное 2.0, среднее 1.92.
        * от **Евгения Лапенкова** до всех игроков КХЛ. Максимальное расстояние 3, медианное 2.0, среднее 1.88.
        * от **Либора Касика** до всех игроков КХЛ. Максимальное расстояние 4, медианное 2.0, среднее 2.48.
* **Визуализация графов.**
    * Создан граф Топ-75 игроков по количеству одноклубников, визуализация графа осуществлена библиотекой Networkx.
    * Создан граф Топ-10 игроков по количеству одноклубников, визуализация графа осуществлена библиотекой Holoview.
    * Создан граф Топ-5 игроков по количеству одноклубников, визуализация графа осуществлена библиотекой Holoview.
* **Проверены гипотезы.**
    *  **Гипотеза 1** о том, что Лемтюгов – самый популярный хоккеист в лиге, то есть обладающий самым большим количеством одноклубников. Если это не так, составить список наиболее популярных игроков. Гипотеза не подтверждена.
        * Ход нашего исследования показал, что у Николая Лемтюгова было 357 одноклубников, это только 71 место по данному показателю. Составлен топ-10 популярных игроков. **Гипотеза не подтверждена.**
    *  **Гипотеза 2.** Правда ли, что игроки с низким значением числа Лемтюгова играли в среднем в большем количестве команд, чем игроки, у которых это значение больше?
        * Из сравнения средних и медиан по количеству одноклубников видно, что игроки с низким значением числа Лемтюгова играли в среднем в большем количестве команд, чем игроки, у которых это значение выше. **Гипотеза подтверждена.**
    * **Гипотеза 3.** Есть ли игроки, у которых отсутствует число Лемтюгова (нет связей через других игроков)?
        * Ранее в ходе нашего исследования для всех игроков КХЛ (3720 человек) было найдено число Лемтюгова, что говорит нам о том, что **нет** игроков, у которых отсутствует число Лемтюгова (нет связей через других игроков). **Гипотеза не подтверждена.**
    *  **Гипотеза 4.** Есть ли связь между количеством переходов и ростом/весом игрока (предполагаем, что игроки, у которых рост выше, лучше играют в хоккей и соответственно чаще переходят из клуба в клуб)?
        * Рассмотрев разные комбинации (рост и вес выше/ниже среднего, рост выше/ниже среднего, вес выше/ниже среднего) нельзя утверждать, что рост или вес сильно влияют на количество трансферов у игроков, однако замечена слабая корреляция между весом и количеством трансферов. Из наблюдений по весу ниже/выше среднего, можно заметить, что при весе выше среднего количество трансферов выше, возможно игроки, набравшие лишний вес менее привлекательны для команд, что способствует их переходу в другие команды. **Гипотеза не подтверждена.**
    *  **Гипотеза 5.** Более успешные хоккеисты рождаются в январе-марте.
        * На примере всех когорт хоккеистов, не удалось обнаружить статистически значимые различия в успешности игроков, родившихся в разные месяцы. **Гипотеза не подтверждена.**


